= Garden

This is my digital garden – a collection of bookmarks, notes, thoughts, and
ideas, a sort of personal knowledgebase.

My digital garden is a perpetual work-in-progress, a series living documents
that I update and refine incrementally. I use Asciidoc to format my notes. I
write atomic notes, which means that each `.adoc` file focused on a single idea
or concept. Topics may cross-reference one another, but each note is
self-contained.

Like any garden, a digital one requires planning and regular maintenance. I
am selective about which topics get added to my garden, and where I place them,
and I regularly weed out notes that are no longer relevant or useful to me.

link:https://maggieappleton.com/garden-history[See Maggie Appleton's essay] on
the concept of the digital garden.

* link:./languages/README.adoc[*Languages*] — all types of computer languages

* link:./platforms/README.adoc[*Platforms*] — software runtime environments, including operating systems

* link:./hardware/README.adoc[*Hardware*] — physical computing devices

* link:./infrastructure/README.adoc[*Infrastructure*] — hardware, networking, cloud

* link:./applications/README.adoc[*Applications*] — software applications

* link:./services/README.adoc[*Services*] — web services, APIs, and other online services

* link:./utilities/README.adoc[*Utilities*] — utility software

* link:./tools/README.adoc[*Tools*] — software development tools

* link:./assets/README.adoc[*Assets*] — digital assets, including fonts, icons, and images

* link:./methods/README.adoc[*Methods*] — software development methodologies and practices



''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[CC0 license]
