= Garden

This is my digital garden – a collection of bookmarks, notes, thoughts, and
ideas.

A digital garden can be thought of as a personal knowledgebase. In knowledge
work, like software development, it can be useful to have a system for managing
and cultivating your knowledge. A digital garden is a way to do that.

My digital garden is a perpetual work-in-progress, a series living documents
that I update and refine incrementally. Most documents are in the AsciiDoc
format. I write atomic documents, which means that each `.adoc` file is focused
on a single idea or concept. Topics may cross-reference one another, but each
document is self-contained.

Like any garden, a digital one requires planning and regular maintenance. I
am selective about which topics get added to my garden, and where I place them,
and I regularly weed out documents that are no longer relevant or useful to me.

See link:https://maggieappleton.com/garden-history[Maggie Appleton's essay] on
the concept of the digital garden.

link:./src[*Contents 🡒*]

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[CC0 license]
