= Garden

This is my digital garden – a collection of bookmarks, notes, thoughts, and
ideas.

A digital garden can be thought of as a personal knowledgebase. In knowledge
work, like software development, it can be useful to have a system for managing
and cultivating your knowledge. A digital garden is a way to do that.

My digital garden is a perpetual work-in-progress, a series living documents
that I update and refine incrementally. Most documents are in the AsciiDoc
format. I write atomic documents, which means that each `.adoc` file is focused
on a single idea or concept. Topics may cross-reference one another, but each
document is self-contained.

Like any garden, a digital one requires planning and regular maintenance. I
am selective about which topics get added to my garden, and where I place them,
and I regularly weed out documents that are no longer relevant or useful to me.

link:https://maggieappleton.com/garden-history[See Maggie Appleton's essay] on
the concept of the digital garden.

== Legend

* 🌱 *Seedling* — rough notes and early ideas that need a lot more work

* 🌿 *Budding* — these notes have been cleaned up and worked on a bit

* 🌳 *Evergreen* — these notes are up-to-date, or finished for the time being

== Categories

* link:./languages/README.adoc[*Languages*] — all types of computer languages

* link:./platforms/README.adoc[*Platforms*] — software runtime environments, including operating systems

* link:./hardware/README.adoc[*Hardware*] — physical computing devices

* link:./infrastructure/README.adoc[*Infrastructure*] — networking, cloud

* link:./applications/README.adoc[*Applications*] — software applications

* link:./services/README.adoc[*Services*] — web services, APIs, and other online services

* link:./utilities/README.adoc[*Utilities*] — utility software

* link:./tools/README.adoc[*Tools*] — software development tools

* link:./assets/README.adoc[*Assets*] — digital assets, including fonts, icons, and images

* link:./methods/README.adoc[*Methods*] — software development methodologies and practices

* link:./media/README.adoc[*Media*] — blogs, podcasts, and other media

== Index

* link:./hardware/processor-architectures.adoc[Processor architectures 🌱]

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[CC0 license]
