= Processor architectures

== x86-64

x86-64 architecture is also known as x86_64, x86-64, x64, or amd64. This refer
to a family of processors based on the Intel 8086 and which are compatible with
the 64-bit CPU architecture used in modern Intel and AMD processors.

x86 started out as a 16-bit instruction set for 16-bit processors, starting with
the Intel 8086 launched in 1978, a 16-bit extension of Intel's early 8-bit
microprocessors. Later this was extended to a 32-bit instruction set for 32-bit
processors (80386 and 80486), and more recently to a 64-bit instruction set for
64-bit processors.

It used to be written as "80x86" to reflect the changing value in the middle of
the chip model numbers, but somewhere in time the 80 prefix was dropped leaving
just x86, referencing only the last two digits of the early successors to the
Intel 8086. Confusingly, the same family of processors is sometimes also referred
to as i386 or i686, while x64 is often used as shorthand for the modern 64-bit
versions, x86-64. Basically, all these terms refer to processors that use
extensions of the original 8086 instruction set.

== Related links

* http://en.wikipedia.org/wiki/IA-32
* http://en.wikipedia.org/wiki/IA-32
* http://en.wikipedia.org/wiki/X86
