= Alerting

Alerting is an extension of *xref:monitoring.adoc[monitoring]* activities. It is
the process of notifying responsible parties when a system is not behaving as
expected, as determined by pre-defined thresholds or conditions around system
*xref:metrics.adoc[metrics]* or *xref:logging.adoc[logs]*.

For example, alerts may be configured for sudden surges in traffic, high error
rates, or a high number of consecutive failed login attempts. It is a
requirement for such alerts to be delivered in near real-time.

Alerting systems tend to be built into *xref:monitoring.adoc[monitoring]* and
*xref:observability.adoc[observability]* systems. For example, Prometheus has
https://prometheus.io/docs/alerting/latest/overview/[Alert Manager], while
Elasticsearch has
https://www.elastic.co/guide/en/elasticsearch/reference/current/watcher-getting-started.html[Watcher].
However, there are a few standalone alerting systems that are designed to feed
off data produced by monitoring and observability tools like Prometheus and the
Elastic stack. Examples include:

* https://www.pagerduty.com/[PagerDuty]: Alerting and incident management
  services.
* https://www.atlassian.com/software/opsgenie[OpsGenie]: Alerting and on-call
  management, part of the Atlassian suite.
* VictorOps: Was an on-call management system and is now part of
  https://www.splunk.com/[Splunk].
