= Complexity

// TODO

== Essential complexity

All systems are complex because all systems have *essential complexity*.
Essential complexity is the complexity that is inherent in the *[problem]* that
the system is trying to solve, or the *xref:domain.adoc[domain]* of the
software.

For example, a system that is trying to solve the problem of routing packets
across a network will have to deal with the inherent complexity of routing
algorithms, network topologies, and so on.

You can't eliminate essential complexity in a system, but you can reduce it by
reducing the scope of the problem you're trying to solve.

== Accidental complexity

*Accidental complexity* is the type of complexity in software systems that
developers have more control over. This is the complexity that comes from the
decisions the developers choose to make in the
*xref:system-design.adoc[system design]*.

Different architectural styles, design patterns, programming paradigms,
application frameworks, and runtime environments – all of these things make
trade-offs between competing *[qualities]*, and therefore bring different types
of accidental complexity into a solution.

For example, *xref:distributed-system.adoc[distributed software]* is inherently
more complex than *[monolithic software]*. A distributed program has to deal
with the complexities of network communication, data consistency, and fault
tolerance. Add *xref:asynchronous-communication.adoc[asynchronous]*
*xref:inter-process-communication.adoc[inter-process communication]* to the mix,
and you have even more complexity that requires specialist tools and techniques
– like *xref:observability.adoc[observability]* and especially
*xref:tracing.adoc[distributed tracing]* – to deal with.
