= Command Query Responsibility Segregation (CQRS)

Command Query Responsibility Segregation (CQRS) is a
*xref:design-principles.adoc[design principle]* and *[pattern]* that proposes
the separation of command handling (write) logic from query (read) logic. It is
an architectural application of *xref:command-query-separation.adoc[command query separation]*,
lifting the method-level principle to the level of separate models. This
allows for the independent optimization of both aspects, enhancing performance
and scalability.

CQRS works well with *xref:event-sourcing.adoc[event sourcing]*, as queries can
be constructed from events, allowing for:

* *Horizontal scalability*: Read and write operations can be scaled
  independently.

* *Eventual consistency*: Although read views may not immediately reflect
  changes in state (as is typical in distributed software), they will eventually
  synchronize.

// TODO: https://newsletter.fractionalarchitect.io/p/28-cqrs-myth-busted-separating-commands
