= Diagramming

:link-staruml:      http://staruml.io/
:link-conceptdraw:  https://www.conceptdraw.com/products/drawing-tool/
:link-dia:          http://dia-installer.de/
:link-diagrams-net: https://app.diagrams.net/
:link-gliffy:       https://www.gliffy.com/
:link-jetuml:       https://www.jetuml.org/
:link-lucidchart:   https://www.lucidchart.com/
:link-omnigraffle:  https://www.omnigroup.com/omnigraffle/
:link-smartdraw:    https://app.smartdraw.com/
:link-umlet:        https://www.umlet.com/
:link-umletino:     https://www.umletino.com/
:link-visio:        https://microsoft.com/en-ca/microsoft-365/visio
:link-yed:          http://www.yworks.com/products/yed
:link-yed-online:   https://www.yworks.com/yed-live/
:link-graphml-wiki: https://en.wikipedia.org/wiki/GraphML
:link-abacus:       https://www.avolutionsoftware.com/abacus/
:link-aplas:        https://aplas.com/
:link-arcentry:     https://arcentry.com/
:link-cacoo:        https://nulab.com/cacoo/
:link-casecomplete: http://casecomplete.com/
:link-cloudcraft:   https://www.cloudcraft.co/
:link-cloudockit:   https://www.cloudockit.com/
:link-cloudskew:    https://www.cloudskew.com/
:link-cloudviz:     https://cloudviz.io/
:link-creately:     https://creately.com/
:link-excalidraw:   https://excalidraw.com/
:link-figjam:       https://www.figma.com/figjam/
:link-gg-charts:    https://gg-charts.com/
:link-hava:         https://www.hava.io/
:link-holori:       https://holori.com/
:link-hyperglance:  https://www.hyperglance.com/
:link-isoflow:      https://isoflow.io/
:link-miro:         https://miro.com/
:link-mural:        https://mural.co/
:link-revision:     https://revision.app/
:link-sketchboard:  https://sketchboard.io/
:link-whimsical:    https://whimsical.com/
:link-aws-icons:    https://aws.amazon.com/architecture/icons/
:link-azure-icons:  https://learn.microsoft.com/en-us/azure/architecture/icons/
:link-gcp-icons:    https://cloud.google.com/icons
:link-k8s-icons:    https://github.com/kubernetes/community/tree/master/icons

Our industry's current bias towards xref:agile.adoc[*agile*] software delivery practices has led to a preference for use
of lightweight diagramming tools to create visual representations of xref:system-design.adoc[*system designs*], over the
production of detailed xref:modeling.adoc[*models*].

Diagrams are often used to communicate ideas and concepts to a wider audience, including non-technical stakeholders,
rather than as a pure development tool.

The *[domain language]* of diagramming tools is "boxes and arrows". This makes diagraming tools relatively easy to use.
The barriers to entry are much lower than for proper modeling tools like {link-staruml}[StarUML]. But this simplicity
has some trade-offs.

* With diagrams, you can't enforce the same level of consistency in naming and relationships between components as you can
  with proper models.

* You can't validate, in an automated way, that diagrams are a correct representation of the code they document.

* You can't query diagrams (eg. "show me all the dependencies of component X").

* You can't auto-generate code from diagrams.

* Maintaining diagrams as the code changes is a more manual, and therefore more error-prone, process compared to
  maintaining models. For example, if you change the name of a class in the code, you will probably have to change it in
  several places in the diagrams, too. In a model, you should need to change the names of things in only one place.

Diagrams tend to be stored in either binary formats (such as images) or heavyweight plain-text formats that are
difficult to diff. For these reasons, it is harder to maintain diagrams under version control systems like Git. But this
is true of many modeling tools, too.

== Diagramming tools

=== Drag-and-drop diagramming tools

Drag-and-drop diagramming tools include:

* {link-conceptdraw}[ConceptDraw Diagram]: Previously known as ConceptDraw Pro, this is a proprietary, general-purpose
  diagramming desktop application.

* {link-dia}[Dia]: Free and open-source general-purpose diagramming tool, with a similar interface to GIMP and Inkscape.

* {link-diagrams-net}[Diagrams.net] (formerly Draw.io): Popular free web app, that's also available as an Electron-based
  cross-platform desktop application. It is also available as a plugin for other applications including Atlassian
  Confluence and Jira, and Visual Studio Code.

* {link-gliffy}[Gliffy]: Easy-to-use web-based diagramming application, supporting collaborative editing and a large
  number of diagram types.

* {link-jetuml}[JetUML]: Free and open-source UML diagramming tool. Supports a limited set of UML diagrams. Saves diagrams
  to a JSON schema, and exports to a variety of image formats.

* {link-lucidchart}[Lucidchart]: Popular diagramming software-as-a-service.

* {link-omnigraffle}[OmniGraffle]: Mac-only diagramming tool and lightweight general-purpose drawing tool.

* {link-smartdraw}[SmartDraw]: Another general-purpose diagramming and visualization software-as-a-service.

* {link-umlet}[UMLet]: A flyweight, free and open-source UML drawing tool. Available as a standalone cross-platform
  application, or an Eclipse plugin, and more recently as an extension to VS Code. It's also available as a free-to-access
  web app called {link-umletino}[UMLetino].

* {link-visio}[Visio]: Collaborative diagramming tool. Accessible via Microsoft 365 commercial subscriptions only (not
  available via personal subscriptions).

* {link-yed}[yEd]: Free (but proprietary) cross-platform desktop and {link-yed-online}[online] diagramming tool. Loads and
  saves diagrams from/to {link-graphml-wiki}[GraphML]. Desktop version requires a local JRE.

=== Diagrams-as-code solutions

Diagrams-as-code solutions are becoming increasingly popular as the plain-text syntax can be version controlled and
maintained alongside the source code they document.

See xref:diagrams-as-code.adoc[*diagrams-as-code*] for a list of solutions.

=== Other diagramming tools

* {link-abacus}[Abacus]: Enterprise architecture tool that includes diagramming capabilities.

* {link-aplas}[Aplas]: Commercial "software mapping" tool.

* {link-arcentry}[Arcentry]: Cloud architecture diagramming tool.

* {link-cacoo}[Cacoo] by Nulab: Web-based collaborative whiteboards.

* {link-casecomplete}[CaseComplete]: Requirements management tool to create use case diagrams, GUI wireframes, and user
  journey flowcharts.

* {link-cloudcraft}[Cloudcraft]: Cloud architecture diagramming tool.

* {link-cloudockit}[Cloudockit]: Cloud architecture diagramming tool.

* {link-cloudskew}[CloudSkew]: Cloud architecture diagramming tool.

* {link-cloudviz}[Cloudviz]: Cloud architecture diagramming tool.

* {link-creately}[Creately]: General-purpose whiteboard tool that supports a wide range of standard diagram types.

* {link-excalidraw}[Excalidraw]: Free online lines-and-boxes drawing tool. Supports Mermaid, and also available as
  JavaScript libraries for integration into other applications.

* {link-figjam}[Figma FigJam]: Brainstorming and collaboration tool that includes diagramming capabilities.

* {link-gg-charts}[gg]: Free web-based charting tool.

* {link-hava}[Hava]: Automatically creates visual representations of your cloud architecture, by dynamically integrating
  with your AWS, Azure, or GCP account.

* {link-holori}[Holori]: Cloud infrastructure planning tool, includes diagramming for AWS, Azure, and GCP.

* {link-hyperglance}[Hyperglance]: Cloud architecture diagramming tool.

* {link-isoflow}[Isoflow]: Network diagrams.

* {link-miro}[Miro]: Web-based whiteboard tool that includes diagramming capabilities.

* {link-mural}[Mural]: Web-based whiteboard tool that includes diagramming capabilities.

* {link-revision}[Revision]: Niche online diagramming software-as-a-service.

* {link-sketchboard}[Sketchboard]: Web-based collaborative whiteboards.

* {link-whimsical}[Whimsical]: Web-based collaborative whiteboards.

=== Icon sets

* {link-aws-icons}[AWS architecture icons]
* {link-azure-icons}[Azure architecture icons]
* {link-gcp-icons}[Google Cloud architecture icons]
* {link-k8s-icons}[Kubernetes icons]

== See also

* xref:modeling-notations-and-methods.adoc[*Modeling notations and methods*]

