= Hexagonal architecture

:link-thoughtworks-demystify: https://www.thoughtworks.com/en-gb/insights/blog/architecture/demystify-software-architecture-patterns
:link-cockburn-article:       https://alistair.cockburn.us/hexagonal-architecture/
:link-cockburn-original:      https://alistair.cockburn.us/Hexagonal+architecture
:link-fideloper:              https://fideloper.com/hexagonal-architecture
:link-reddit-php:             https://www.reddit.com/r/PHP/comments/29bprf/hexagonal_architecture/
:link-garrido-articles:       https://jmgarridopaz.github.io/content/articles.html
:link-buenosvinos:            https://carlosbuenosvinos.com/hexagonal-architecture-with-php-was-published-in-phparch-magazine/
:link-phparch-magazine:       https://www.phparch.com/2014/07/july-2014-phparchitect-magazine-released-navigating-the-business/

// TODO: https://www.thoughtworks.com/en-gb/insights/blog/architecture/demystify-software-architecture-patterns
// TODO: https://alistair.cockburn.us/hexagonal-architecture
// TODO: https://jmgarridopaz.github.io/content/hexagonalarchitecture.html
// TODO: https://jmgarridopaz.github.io/content/hexagonalarchitecture-ig/intro.html
// TODO: https://jmgarridopaz.github.io/content/therightboundary.html
// TODO: https://jmgarridopaz.github.io/content/whathais.html
// TODO: https://jmgarridopaz.github.io/content/hapills.html#tc2
// TODO: https://medium.com/booking-com-development/hexagonal-architecture-a-practical-guide-5bc6d5a6a056

{link-cockburn-article}[Hexagonal architecture] is a software *[architectural design pattern]* devised by Alistair
Cockburn in 2005.

Conceptually, hexagonal architecture is similar to Jeffrey Palermo's xref:onion-architecture.adoc[*onion architecture*]
(2008) and Robert C Martin's xref:clean-architecture.adoc[*clean architecture*] (2012). All these architectural concepts
share the same fundamental objective: the xref:separation-of-concerns.adoc[*separation of concerns*], achieved by
slicing systems into discrete *[layers]* and applying the *[dependency inversion principle]* at the boundaries between
the layers.

Hexagonal architecture is defined as a system that uses the xref:ports-and-adapters.adoc[*ports and adapters*] pattern
to model _all_ inputs to, and _all_ outputs from, _all_ the components of a system. The ports-and-adapters pattern is
thus used for _every_ interface that a software component has with the outside world.

An application will typically have many different inputs and outputs.

image::hexagonal-architecture.svg[Hexagonal architecture]

The choice of a hexagonal shape to represent this architectural concept is arbitrary. It suggests there are typically
multiple inputs on the "driving" side of an application and multiple outputs on its "driven" side. In the context of
xref:distributed-system.adoc[*distributed software*] or xref:modular-monolith.adoc[*modular monoliths*], multiple
services or components may interface with each other through connections made via their ports (using adapters), so the
whole system – from a *[conceptual]* view – forms a honeycomb pattern.

image::honeycomb-pattern.svg[Honeycomb pattern]

Hexagonal architecture shares some similarities with domain-driven design, and indeed the two architectural styles can
be combined. Like domain-driven design, hexagonal architecture proposes that software components are built around a core
model of their domain. The central domain layer encapsulates the business logic.

== Pros and cons of hexagonal architecture

[quote, Alistair Cockburn]
____
Allow an application to equally be driven by users, programs, automated test or
batch scripts, and to be developed and tested in isolation from its eventual
run-time devices and databases.
____

One of the main advantages of hexagonal architecture is *[testability]*. Because all dependencies are hidden behind
abstractions by design, it makes it easy to mock external systems, including GUIs and other input interfaces. All you
need to do is create special mock adapters that fit the same ports as the real adapters.

Another benefit is xref:evolvability.adoc[*evolvability*]. It becomes possible, for example, to change from a
human-driven use of an application to batch-driven use. You just plug in different adapters to the existing ports.
Likewise, it is relatively easy to change dependencies. For example, you can migrate from MySQL to PostgreSQL by
changing the database adapter.

For the same reason, applications become less tightly coupled to any particular infrastructure or host environment.
Thus, applications are more *[portable].*

For the ports-and-adapters pattern to effectively deliver these promised benefits, it is important that business logic
does not leak into the ports-and-adapters layer. This is the same constraint as for *[n-tier architecture]*, in which
business logic should not leak into either the uppermost UI/presentation layer or the bottommost persistence layer.

The main trade-off is that hexagonal architecture adds a lot of xref:complexity.adoc[*accidental complexity*]. There is
more code to maintain, and potentially more effort involved in running applications in development and other
environments. This additional complexity may not be worthwhile for small, trivial applications.

== See also

* xref:clean-architecture.adoc[*Clean architecture*]
* xref:design-pattern.adoc[*Design patterns*]
* xref:domain-driven-design.adoc[*Domain-driven design*]
* xref:layered-architecture.adoc[*Layered architecture*]
* xref:onion-architecture.adoc[*Onion architecture*]

== References

* Cockburn, Alistair (2005).
  {link-cockburn-original}[_Hexagonal architecture_].

* Fidao, Chris.
  {link-fideloper}[_Hexagonal architecture_].

* Garrido de Paz, Juan Manuel.
  {link-garrido-articles}[_Hexagonal Me_].

* Buenosvinos, Carlos (2014).
  {link-buenosvinos}[_Hexagonal Architecture with PHP_].
  {link-phparch-magazine}[php[arch\]].

* Thoughtworks.
  {link-thoughtworks-demystify}[_Demystifying software architecture patterns_].
