= Inversion of control (IoC)

:link-fowler-ioc:        https://martinfowler.com/articles/injection.html
:link-brett-servlocator: https://adamcod.es/2013/11/25/service-locator-vs-dependency-injection-container.html
:link-miller-di:         https://richardmiller.co.uk/2011/07/07/dependency-injection-moving-from-basics-to-container/

Inversion of control (IoC) is a xref:design-principle.adoc[*design principle*] in which the control flow of a program is
somehow inverted.

In traditional programming, the main program is in control of the flow of the program. In IoC, the flow is inverted, and
the control is given to a framework or runtime environment. The xref:spring-framework.adoc[*Spring Framework*] is a
well-known IoC container for Java applications.

Various xref:design-pattern.adoc[*design patterns*] can be used to implement IoC, such as the
xref:dependency-injection.adoc[*dependency injection*] and xref:publish-subscribe-pattern.adoc[*publish-subscribe*]
patterns. xref:dependency-inversion.adoc[*Dependency inversion*] is one principle that IoC puts into practice by
inverting the direction of dependencies between modules.

== See also

* {link-fowler-ioc}[Inversion of Control Containers and the Dependency Injection Pattern],
  Martin Fowler, 2004.

* {link-brett-servlocator}[Service Locator vs Dependency Injection Container (or Tell, Don't Ask Part 2)],
  Adam Brett, 2013

* {link-miller-di}[Why use a Dependency Injection Container?],
  Richard Miller, 2011

