= Monitoring

:link-datadog:    https://www.datadoghq.com/
:link-grafana:    https://grafana.com/
:link-nagios:     https://www.nagios.org/
:link-prometheus: https://prometheus.io/
:link-zabbix:     https://www.zabbix.com/

Monitoring is the process of collecting, analyzing, and using data to track the
xref:performance.adoc[*performance*] and health of a system.

Monitoring is typically focused on collecting logs and xref:metrics.adoc[*metrics*] – things like
CPU usage, memory consumption, error rates, and response times – to provide insights into a system's
state. The primary goal of monitoring is to detect and alert on predefined issues or failures within
a system.

Monitoring is closely associated with xref:observability.adoc[*observability*]. The same tools and
data can be used for both, but the two concepts are distinct. Monitoring is a _reactive_ process,
reacting to events and changes in state based on pre-configured rules. Observability is a
_proactive_ process, focused instead on analyzing a systems behavior and performance after the fact.

Monitoring can be implemented at various levels of a system, including:

* *Infrastructure monitoring*: Focuses on tracking the health and performance of underlying
  infrastructure like servers, containers, and virtual machines, through metrics like
  xref:uptime.adoc[*uptime*], CPU utilization, memory utilization, disk I/O, and more.

* *Network monitoring*: Tracks network health, including bandwidth utilization, packet loss,
  latency, roundtrip time, and potential security threats.

* xref:application-performance-management.adoc[*Application performance management (APM)*]: Monitors
  specific software applications, tracking metrics like response times, resource usage, error rate,
  and various business-specific metrics.

* *Database monitoring*: Focuses on query performance, cache hit ratios, number of connections,
  storage utilization, and more.

== Monitoring tools

* {link-datadog}[Datadog]: Popular monitoring and analytics service (proprietary).
* {link-grafana}[Grafana]: An open-source analytics and monitoring platform.
* {link-nagios}[Nagios]: A monitoring and alerting system for networks, servers, and
  applications.
* {link-prometheus}[Prometheus]: An open-source monitoring and alerting toolkit.
* {link-zabbix}[Zabbix]: An open-source monitoring tool, also available as a subscription
  service.

See also xref:observability.adoc[*Observability*] tools, many of which include monitoring
capabilities.

== See also

* xref:alerting.adoc[*Alerting*]
* xref:logging.adoc[*Logging*]
* xref:system-health-checks.adoc[*System health checks*]
* xref:telemetry.adoc[*Telemetry*]
* xref:time-series-databases.adoc[*Time series databases*]
* xref:visibility.adoc[*Visibility*]
