= NoSQL databases

// TODO: https://www.integrate.io/blog/the-sql-vs-nosql-difference/
// TODO: https://blog.algomaster.io/p/sql-vs-nosql-7-key-differences

"NoSQL" is an umbrella term for a range of non-relational databases, ie.
database designs that are not based on the traditional model of
*xref:relational-databases.adoc[relational]*, tabular data. NoSQL refers to any
database management system that is based on schema-less data models, and
therefore does not require stored data to be highly structured.

NoSQL databases have varied data storage models. The four main types are:

* *xref:document-oriented-databases.adoc[Document-oriented databases]*
* *xref:graph-databases.adoc[Graph databases]*
* *xref:key-value-stores.adoc[Key-value stores]*
* *xref:wide-column-stores.adoc[Wide-column stores]*

Other types of NoSQL databases include
*xref:time-series-databases.adoc[time-series databases]*.

NoSQL databases offer more flexibility and easier horizontal scalability than
relational databases, but may sacrifice some of the
*xref:data-integrity.adoc[data integrity]* and
*xref:acid-principles.adoc[transactional guarantees]* of relational databases.

NoSQL is suited for handling large volumes of unstructured or semi-structured
data (in which data structures may be changed, to some degree, on a per-record
basis), and for applications requiring quick iterations in the design of their
*xref:data-modeling.adoc[data model]*. This makes NoSQL a common choice for xref:big-data.adoc[*big data*]
workloads.

Compared to *xref:relational-databases.adoc[relational databases]*, NoSQL
databases are more amenable to
*xref:horizontal-scaling.adoc[horizontal scaling]*. Indeed, some NoSQL databases
are designed specifically to run as xref:distributed-databases.adoc[*distributed databases*].
Examples include Cassandra and MongoDB.

Another way to classify databases is between
*xref:transactional-databases.adoc[transactional or operational databases]* and
*xref:analytical-databases.adoc[analytical databases]*.

== See also

* xref:databases.adoc[*Databases*]
* *xref:relational-databases.adoc[Relational databases]*
