= Ontology

An ontology is any formal representation of a set of concepts and categories in
a subject area or xref:domain.adoc[*domain*]. It describes the concepts and
relationships between them, and can be used to
xref:domain-engineering.adoc[*model a domain*], a subdomain, or a specific
problem.

In xref:domain-driven-design.adoc[*domain-driven design*], ontologies map to the
concept of xref:ubiquitous-language.adoc[*ubiquitous language*]. The ubiquitous
language is a shared vocabulary that all stakeholders in a project agree on, and
it is used to describe all aspects of the domain (or, in complex domains, a
group of subdomains defined by a xref:bounded-context.adoc[*bounded context*]).

Standards like RDF, RDF Schema, and the Web Ontology Language (OWL) can be used
to create and reason about ontologies. Ontologies built on these standards are
often stored and queried in xref:graph-databases.adoc[*graph databases*] known
as RDF triple stores. Software modeling languages like UML can also be used for
this purpose, for example class diagrams could be used to represent concepts
and the relationships between them.

*[Protégé]* is a free and open-source ontology editor and knowledge management
system. It supports OWL and RDF.

*[HybridMDSD]* is a tool that integrates different domain-specific modeling
languages based on their ontological foundations.

== See also

* xref:knowledge-graph.adoc[*Knowledge graph*]
* xref:json-ld.adoc[*JSON-LD*]
