= Package principles

The *package principles* are a  set of five xref:design-principle.adoc[*design principles*] formulated by Robert C Martin,
who also coined the *SOLID* acronym. Whereas the SOLID principles target the level of classes, the package principles
target the level of larger components that contain multiple classes — packages or modules. The principles can be applied
at even larger scales, too, such as at the level of independently-deployable services.

The package principles are:

* xref:reuse-release-equivalence.adoc[*Reuse/release equivalence principle (REP)*]
* xref:common-reuse-principle.adoc[*Common reuse principle (CRP)*]
* xref:common-closure-principle.adoc[*Common closure principle (CCP)*]
* xref:acyclic-dependencies-principle.adoc[*Acyclic dependencies principle (ADP)*]
* xref:stable-dependencies.adoc[*Stable dependencies principle (SDP)*]
* xref:stable-abstractions.adoc[*Stable abstractions principle (SAP)*]

The package and SOLID principles share the goals of keeping software maintainable and avoiding the symptoms of degraded
design, such as *rigidity*, *fragility*, *immobility*, and *viscosity*.

The package principles reassert the universal principles of xref:coupling.adoc[*low coupling*],
xref:cohesion.adoc[*high cohesion*], xref:single-responsibility-principle.adoc[*single responsibility*],
*hierarchical (acyclic) decomposition*, and xref:dependency-inversion.adoc[*dependency inversion*].

== See also

* xref:abstractness.adoc[*Abstractness*]
