= Relational database management systems (RDBMS)

// TODO: https://condor.depaul.edu/gandrus/240IT/accesspages/relationships.htm

Relational database management systems (RDBMS), also known as *relational databases* or *SQL databases*, are built on the relational model that stores data against predefined schemas, and structured as interlinked tabular data. Each row in a data table typically maps to an entity or object, and the table's columns define the entity's fields.

These databases are highly structured and offer powerful query languages, usually a form of *xref:sql.adoc[SQL]*, making them ideal for complex queries and *xref:transaction.adoc[transactions]*. Relational databases tend to be *xref:acid-principles.adoc[ACID compliant]*, making them good choices for applications that require *xref:data-integrity.adoc[data integrity]* to be prioritized over performance.

Relational databases can be challenging to scale horizontally. They tend, instead, to be *xref:vertical-scaling.adoc[scaled vertically]* (the capacity of individual nodes is increased as data grows). However, *xref:sharding.adoc[sharding]* can also be used to distribute data horizontally across multiple RDBMS instances.

By comparison, *xref:nosql-databases.adoc[non-relational databases]* (aka NoSQL databases) are more flexible and scalable, but may sacrifice some of the consistency and transactional guarantees of relational databases.

Another way to classify databases is between *xref:transactional-databases.adoc[transactional or operational databases]* and *xref:analytical-databases.adoc[analytical databases]*.

== Examples of relational databases

* MySQL
* PostgreSQL
* SQLite
* Oracle Database

== See also

* *xref:database-query-optimization.adoc[Database query optimization]*
