= Service mesh

A service mesh handles all of the inter-process communication as well as dealing
with service discovery and reliability (load balancing etc).

A service mesh is a dedicated infrastructure layer that manages all aspects of
service-to-service communication within
*xref:distributed-system.adoc[distributed software]*.

Typically, a service mesh will encompass the following features:

* *xref:load-balancing.adoc[Load balancing]*: Distributing traffic evenly across
  *xref:replication.adoc[replicated]* nodes, improving
  *xref:fault-tolerance.adoc[resilience]* to failure of any single node.

* *xref:service-discovery.adoc[Service discovery]*: Allowing services to find
  and communicate with each other, typically through a *service registry*.

* *Routing*, *xref:retry.adoc[retries]*, *circuit breaking* and other traffic
  management responsibilities.

* *xref:security.adoc[Security]*: Handling service-to-service authentication and
  authorization, and encryption of communication channels.

* *xref:observability.adoc[Observability]*: Providing
  *xref:monitoring.adoc[monitoring]* and *xref:tracing.adoc[tracing]*
  capabilities.

Popular service mesh solutions include Istio and Linkerd.
