= Shell

:link-csh:      https://bxr.su/NetBSD/bin/csh/
:link-tcsh:     https://www.tcsh.org/
:link-ksh:      https://www.kornshell.org/
:link-zsh:      https://www.zsh.org/
:link-yash:     https://yash.osdn.jp/
:link-busybox:  https://www.busybox.net/

A shell is a command-line interpreter that provides a user interface for accessing an operating system's services. It
allows users to execute system commands, run utilities and other programs, and manage files and processes on the local
system. The shell interprets user commands and translates them into actions performed by the operating system.

Most shells are both a *command language* (in which commands are typed and executed interactively via the command line)
and a *scripting language* (in which a sequence of commands are written in a file and executed all at once – behaving
more like a program).

Command line interpreters tend to be used for system administration, rather than for software application development.
Bash is a good choice for writing simple, single-purpose system utilities with short execution times, and particularly
excels at automating tasks that involve installing and configuring system software.

Command line interpreters should not be confused with interactive shells or *[REPLs]* for higher-level programming
languages, which have a similar user experience but different use cases.

A *Unix shell* is a shell designed for Unix-like operating systems. Well-known Unix shells include:

* The Bourne Shell, `sh`, one of the earliest shells.
* The xref:bash.adoc[*Bourne Again Shell*], `bash`, a superset of the Bourne Shell.
* {link-csh}[C Shell], `csh`, and the improved version {link-tcsh}[tee-shell], `tcsh`.
* {link-ksh}[KornShell], `ksh`, which is backwards compatible with Bourne Shell and includes many of the features of C
  Shell.
* {link-zsh}[Z Shell], `zsh`, another popular shell based on Bourne.

Lesser-known Unix shells include {link-yash}[Yash] and {link-busybox}[busybox].

== See also

* xref:developer-tooling.adoc[*Developer tooling*]
* xref:posix.adoc[*POSIX*]
* xref:unix.adoc[*Unix*]
* xref:unix-philosophy.adoc[*Unix philosophy*]

