= Structure and Interpretation of Computer Programs

_Structure and Interpretation of Computer Programs_, also known as SICP or the
"wizard book", by Hal Abelson and Jerry Sussman, is a classic book in computer
science that introduces fundamental concepts of programming.

The book is still in print and is also available
https://mitp-content-server.mit.edu/books/content/sectbyfn/books_pres_0/6515/sicp.zip/index.html[for free online].

The book starts out by introducing the base elements of programming – values,
names, binding, control, and so on – and then expands to explore a breadth of
topics including:

* Lambda abstraction and higher-order computation
* Complex structures, including those with embedded computational content
* Modularity
* Mutability
* Streams
* Lazy evaluation
* xref:execution-model.adoc[*Execution models*], interpreters, and compilers
* Storage management, garbage collection, and virtual memory
* Machine code
* xref:domain-specific-language.adoc[*Domain-specific languages*]

== See also

* xref:abstraction.adoc[*Abstraction*]
* xref:programming-paradigm.adoc[*Programming paradigm*]
