= Spring Framework

:link-tomcat:             https://tomcat.apache.org/
:link-jetty:              https://jetty.org/
:link-spring-initializer: https://start.spring.io/

Spring is a popular, comprehensive Java application development framework. Its core is an
xref:inversion-of-control.adoc[*inversion of control*] container that supplies components with their
collaborators through xref:dependency-injection.adoc[*dependency injection*].

== Spring Boot

Spring Boot is a project within the Spring ecosystem that simplifies the configuration and
deployment of Spring applications.

Spring Boot is an abstraction layer on top of the Spring Framework that imposes more opinions on the
application configuration, and in turn eliminates a lot of boilerplate code and configuration that
Spring Framework requires when used directly.

The main goal of the Spring Boot project is to minimize configuration time, enabling developers to
more quickly launch prototypes and production-grade applications. Many of the repetitive tasks
involved in application setup, such as dependency management and the configuration of embedded
servers like {link-tomcat}[Tomcat] or {link-jetty}[Jetty], are more automated by
Spring Boot.

Spring Boot is integrated with many other components of the Spring ecosystem, including Spring Data
and Spring MVC.

{link-spring-initializer}[Spring Initializer] is an online tool that generates a Spring Boot project
template based on the user's selections.

== See also

* xref:inversion-of-control.adoc[*Inversion of control*]
* xref:dependency-injection.adoc[*Dependency injection*]
* xref:developer-tooling.adoc[*Developer tooling*]
