= Spring Framework

Spring is a popular, comprehensive Java application development framework. Its
core is an *xref:inversion-of-control.adoc[inversion of control]* container that
supplies components with their collaborators through
*xref:dependency-injection.adoc[dependency injection]*.

== Spring Boot

Spring Boot is a project within the Spring ecosystem that simplifies the
configuration and deployment of Spring applications.

Spring Boot is an abstraction layer on top of the Spring Framework that imposes
more opinions on the application configuration, and in turn eliminates a lot of
boilerplate code and configuration that Spring Framework requires when used
directly.

The main goal of the Spring Boot project is to minimize configuration time,
enabling developers to more quickly launch prototypes and production-grade
applications. Many of the repetitive tasks involved in application setup, such
as dependency management and the configuration of embedded servers like
https://tomcat.apache.org/[Tomcat] or https://jetty.org/[Jetty], are more
automated by Spring Boot.

Spring Boot is integrated with many other components of the Spring ecosystem,
including Spring Data and Spring MVC.

https://start.spring.io/[Spring Initializer] is an online tool that generates a
Spring Boot project template based on the user's selections.
