= Throughput (aka. bandwidth)

// TODO: https://aws.amazon.com/compare/the-difference-between-throughput-and-latency/

Throughput is a measure of the amount of work done, or the amount of data
processed, in a given amount of time. It is also known as bandwidth and is
typically expressed in terms of requests per second (RPS) or transactions per
second (TPS).

As a xref:quality-attributes.adoc[*quality attribute*] of
xref:distributed-system.adoc[*distributed software*], trade-offs may be made
with xref:latency.adoc[*latency*]. For example, to increase throughput you might
xref:batch-processing.adoc[*batch*] requests together, process data in xref:parallelism.adoc[*parallel*],
or xref:load-balancing.adoc[*spread load*] across multiple servers. But these strategies can have the
effect of increasing the time individual requests spend waiting in queues,
thereby increasing latency. Raising throughput by adding resources does not in
itself improve xref:efficiency.adoc[*efficiency*], which is the ratio of useful
output to the resources consumed to produce it.

image::latency-vs-throughput.svg[]

== See also

* xref:replication.adoc[*Replication*]
* xref:rtt.adoc[*Round-trip time (RTT)*]
