= Trunk-based development

:link-paul-hammant:      https://github.com/paul-hammant
:link-trunkbaseddev-org: https://trunkbaseddevelopment.com/

Trunk-based development (TBD) is a xref:version-control.adoc[*source control*] branching model that
encourages small increments of work to be integrated regularly into a shared mainline branch –
commonly called `trunk`, `master`, or `main`. It is a concrete application of the
xref:commit-early-commit-often.adoc[*commit early, commit often*] principle, with frequent
integration into the mainline as the cadence.

Trunk-based development attempts to avoid xref:big-bang.adoc[*big-bang*] merges, and the increased
risks of merge conflicts that come with those. This is done by adhering to the following principles:

* Keep all work-in-progress close to the trunk branch.
* Integrate small, stable changes into the trunk branch as quickly as possible.
* *Never break the build* (the golden rule of TBD): keep the trunk branch in a deployable state at
  all times, by running automated tests prior to commits being added to the trunk (either locally or
  via pull request pipelines).

Trunk-based development enables xref:continuous-integration.adoc[*continuous integration*] and (by
extension) xref:continuous-delivery.adoc[*continuous delivery*]. It is supported by techniques such
as xref:feature-flags.adoc[*feature flags*], which replace the need for long-lived side branches to
support feature development. Instead of keeping unfinished features isolated from other developers
using side branches, you keep unfinished features isolated from your end users by disabling the code
in production behind feature toggles.

In internal research, Microsoft found that trunk-based development was the most effective way to
scale its development process. This branching model was used the most effectively across all its
sub-organizations and internal teams.

{link-paul-hammant}[Paul Hammant], a Thoughtworks consultant,
{link-trunkbaseddev-org}[maintains an excellent website] dedicated to the topic of
trunk-based development.

== See also

* xref:big-bang.adoc[*Big-bang*]
* xref:commit-early-commit-often.adoc[*Commit early, commit often*]
* xref:continuous-integration.adoc[*Continuous integration*]
* xref:feature-flags.adoc[*Feature flags*]
* xref:software-delivery-and-operations.adoc[*Software delivery and operations*]
* xref:version-control.adoc[*Version control*]
