= 10x engineer

The concept of the 10x programmer originated in a https://dl.acm.org/doi/10.1145/362851.362858[January 1968 paper], printed in the Communications of the ACM journal, titled "Exploratory experimental studies comparing online and offline programming performance." The paper was subsequently cited by Fred Brooks in his 1975 book, The Mythical Man-Month, popularizing the idea.

The original paper was one of the first attempts to measure programmer productivity in a scientific way. Across different skill levels, years of experience, and task types, the authors found "large individual differences between high and low performers," with the differences being as large as "an order of magnitude" – the most effective programmers were ten times more productive than the least effective ones.

The myth of the 10× programmer – that some people are _orders of magnitude_ more productive at writing code and fixing bugs – was born.

[quote, Sackman et al, Communications of the ACM January 1968]
____
The "horrid" portion of the performance frequency distribution is the long tail at the high level, the positively skewed part which shows that one poor performer can consume as much time as 5, 10, or 20 good ones. Validated techniques to weed out these poor performers could result in vast savings in time, effort, and cost.
____

There are a number of flaws in the study, and the findings have been debunked by subsequent research. Among the criticisms of the study are that it tested programmers on tasks that were not representative of real-world programming, and that it did not account for the impact of teamwork and collaboration that would be present in real-world scenarios.

Nevertheless, the idea of 10x engineers and "rockstars" has persisted in the pop culture of the software industry.

== Related links

* https://matthewstrom.com/writing/beyond-10x/[Beyond 10x], Matt Ström-Awn (2021)
* https://spectrum.ieee.org/10x-engineer[In praise of "normal" engineers], IEEE Spectrum (2025)
