= Analytical databases

Analytical databases are a family of database management systems that are often contrasted with *link:./transactional-databases.adoc[transactional databases]*.

Both analytical and transactional databases may be *link:./nosql-databases.adoc[non-relational]* or *link:./relational-databases.adoc[relational]* – which is another way to classify database management systems.

Analytical databases are used for *Online Analytics Processing (OLAP)*. *[Data warehouses]* may be used for this purpose, with the source data come from the Online Transaction Processing (OLTP) done by *link:./transactional-databases.adoc[transactional databases]*, or other sources.

Analytical databases do not tend to be customer-facing. However, data may be extracted from customer-facing databases into analytical databases for the purpose of decision making.

Compared to transactional databases, the transactions performed in analytics databases tend to be longer and involve more complex queries.

Examples of relational analytical databases include Amazon Redshift, Teradata, and HP Vertica. Examples of non-relational analytical databases include Amazon Elastic MapReduce (EMR) and other Map Reduce databases.
