= Availability

.Availability
****
Every request receives a response, without guaranteeing that it contains the most recent write.
****

Availability is a *link:./quality-attributes.adoc[quality attribute]* that is a measure of the
ability of a system to remain operational and accessible to its users at all times, even under
heavy load and even when parts of the system fail. It is closely related to
*link:./scalability.adoc[scalability]* and *link:./fault-tolerance.adoc[fault tolerance]*.

Availability is typically expressed as a percentage of *link:./uptime.adoc[uptime]* over a given
period. For example, a system that has an uptime of 99.9% is considered to have "three nines of
availability".

What is considered to be "highly available" depends on the system's
*link:./requirements.adoc[requirements]*. A system with three nines of availability would actually
have a *link:./downtime.adoc[downtime]* of 8.76 hours per year, which may be acceptable for some
systems but not for others. 99.99% uptime (four nines) would mean a downtime of 52.56 minutes per
year.
