= Bash

[Bash](https://www.gnu.org/software/bash/) is a Unix link:./shell.adoc[shell].

Brian Fox was the original author of Bash. The language was developed from the late 1980s as a [GNU](https://www.gnu.org/) project, with the aim of making a [free software](https://www.fsf.org/) replacement for the Bourne shell, which was then the standard shell on all Unix systems. Bash's syntax and baseline features are a superset of the Bourne shell, meaning that legacy Bourne `sh` scripts can usually be executed by the Bash shell. (Bash is an acronym for "bourne again shell".)

Bash is still actively maintained and developed, albeit by a single person – Chet Ramey, working on behalf of the Free Software Foundation.

Despite newer shells like [Z shell (Zsh)](https://www.zsh.org/) coming along, Bash remains the most popular shell among users of Linux. It is still the default login shell for most Linux distributions, and it was the default shell in macOS prior to 2019 (when the default shell was swapped to Zsh). A version of Bash is also available for Windows 10+.

Like other Unix shells, Bash itself is not particularly powerful. It's utility comes from the access it gives to other Unix tools.
