= Bottom-up design

Bottom-up design is an approach to *link:./system-design.adoc[system design]* that emphasizes
building systems from small, primitive components, gradually integrating lots of small parts to
compose the complete solution. It is sometimes used as a synonym for [evolutionary design], which
is a similar concept.

Bottom-up design contrasts with *link:./top-down-design.adoc[top-down design]*, which instead
emphasizes up-front planning and design through [decomposition] of the problem space into lots
of subsystems.

Bottom-up design is often desirable in situations where there are limited resources (such as time
or people) or where the requirements are unclear or unstable. The emphasis is on reusing generic
components to compose custom solutions with minimal bespoke code. The base components are linked
together to form larger subsystems, which are in term connected to form the complete system.

The main benefit of bottom-up design is [reusability] of existing code. The main downside of
bottom-up design is that is can be overly organic, leading to a tangle of elements and subsystems
with no overall structure and limited consistency. Development of large-scale systems especially
requires some degree of top-down design to maintain [conceptual integrity]. In practice, most
modern software design practices combine elements of both top-down and bottom-up design.
