= Cloud computing

Cloud computing is a computing model that enables on-demand access to a shared pool of configurable computing resources (eg. networks, servers, storage, and applications) that can be rapidly provisioned and released with minimal management effort.

Cloud computing is a synonym for *data center* based computing through high bandwidth networks. It is closely connected to *virtualization*.

In many ways, modern cloud computing is a return to the roots of computing. In the 1960s, mainframe computers provided computing power to multiple users through *[time-sharing]*.

== Advantages of cloud computing

* *Trade capital expense for variable expense*: A lot of CFOs prefer operational expenditure (OPEX) over capital expenditure (CAPEX), depending on the economic climate. CAPEX is tax deductible over the entire depreciation lifetime of the hardware you buy, while OPEX is tax deductible in the same year.

* *Economies of scale*: Aggregated usage across hundreds of thousands of customers means lower variable costs for individual customers.

* *Stop guessing capacity*: Previously, businesses tended to over-provision hardware resources. It is better to have too much than too little, but the trade-off for the extra cost for availability is wasted capacity. Cloud computing offers elastic resourcing, allowing you to rapidly scale your resources up and down in response to changing needs. Your costs are therefore based on actual usage rather than forecasts.

* *Increase speed and agility*: With cloud, you can deploy resources quickly and easily. And you can react to changing requirements more quickly.

* *Stop spending money* doing your own data center management. Spend that money on innovation instead.

* *Go global in minutes*: It is very easy to deploy applications all over the world.
