= Conway's law

:link-conways-law: https://web.archive.org/web/20190929004831/http://www.melconway.com/Home/Conways_Law.html

Conway's law describes the link between the communication structure of
organizations and the systems those organizations design for their own needs.
The law is named after the computer programmer Melvin Conway, who
{link-conways-law}[introduced the idea in 1967].

[quote, Melvin E Conway, How Do Committees Invent?]
____
Organizations which design systems (in the broad sense used here) are
constrained to produce designs which are copies of the communication structures
of these organizations.
____

The law is based on the reasoning that in order for a product to function, the
authors and designers of its component parts must communicate with each other
in order to ensure compatibility between the components. Therefore, the
technical structure of a system will reflect the social boundaries of the
organizations that produced it, across which communication is more difficult.

In colloquial terms, it means complex products end up "shaped like" the
organizational structure they are designed in, or designed for. The law is
applied primarily in the field of software architecture, though Conway directed
it more broadly and its assumptions and conclusions apply to most technical
fields.

Conway's law is often cited in discussions about the design of software
systems, and methods like *link:./domain-driven-design.adoc[domain-driven design]*
are intended to mitigate its effects.
