= Database modeling

See also *link:./modeling.adoc[modeling]*.

== Tools

The following tools specialize in database modeling. They are used to design database schemas,
including the relationships and constraints in *[SQL databases]*. These are proper
*link:./modeling.adoc[modeling]* tools, not just *link:./diagramming.adoc[diagramming]* tools,
which means they can be used to generate SQL code their their models.

[NOTE]
======
Some *[database administration]* tools such as https://www.heidisql.com/[HeidiSQL] and
https://www.mysql.com/products/workbench/[MySQL Workbench] also support visual database design.
======

* https://www.dbdesigner.net/[DB Designer]:
  Online database design tool.

* https://www.fabforce.net/dbdesigner4/[DbDesigner 4]:
  Open source design tool for MySQL databases.

* https://dbdiagram.io/[Dbdiagram.io]:
  Online database diagram design tool. From data models defined in a lightweight, plain text
  markup language, the UI dynamically renders Entity-Relationship (ER) diagrams and exports
  SQL statements for table creation.

* https://dbschema.com/[DbSchema]:
  Powerful modeling tool for both SQL and NoSQL databases. Supports reverse engineering of
  existing databases, visual query building, generation of dummy test data, and more.

* https://soft-builder.com/erbuilder-data-modeler/[ER Builder Data Modeler]:
  Automatically generates SQL code for popular databases from ER diagrams.
  Desktop software-as-a-service.

* https://www.oracle.com/database/sqldeveloper/technologies/sql-data-modeler/[Oracle SQL Developer Data Modeler]:
  Free graphical tool for designing database schemas.
