= Data-oriented architecture (DOA)

:link-2007-whitepaper: http://community.rti.com/sites/default/files/archive/Data-Oriented_Architecture.pdf
:link-2017-paper: https://dl.acm.org/doi/10.1145/3151759.3151770

// TODO: https://blog.eyas.sh/2020/03/data-oriented-architecture/
// TODO: http://community.rti.com/sites/default/files/archive/Data-Oriented_Architecture.pdf

This architectural style was first described by Rajive Joshi in a {link-2007-whitepaper}[2007 whitepaper] from infrastructure software company Real-Time Innovations (RTI), and later {link-2017-paper}[in a 2017 paper] by Christian Vorhemus and Erich Schikuta at the University of Vienna.

A data-oriented architecture can be summarized as a system that uses a monolithic data store as its main source of state, but in which multiple loosely-coupled stateless services act upon that central store.

Thus, a DOA is a hybrid of *[link:./monolith.adoc[monolithic]* and *link:./service-oriented-architecture.adoc[service-oriented]* (and especially *link:./microservices.adoc[microservice]*) designs.

// TODO: Add diagrams.

Rather than federating data stores for each service, DOA mandates describing the state layer in terms of a single, centrally-managed global data schema.

One of the big advantages of this design pattern is the ease with which data *link:./consistency.adoc[consistency]* can be maintained across the system. And component-to-component interaction is minimized, favouring data sharing through the central store, potentially reducing overall latency in the system.

The main trade-offs are the greater potential for the central data store to become a performance bottleneck and single point of failure. Scaling techniques like sharding and replication can be used to mitigate these risks, but they can be harder to implement in monolithic stores.

// TODO: Add further notes from Eyas Sharaiha's write-up on this architectural style, such as the
// concept of organizing services into consumers and producers of data (similar to CQRS).
// https://blog.eyas.sh/2020/03/data-oriented-architecture/
