= Domain

In IT, the *domain*, also known as a *business domain*, refers to the subject area or sphere of knowledge that determines the requirements of an IT system. The domain is the real-world context in which an IT system will operate, and it defines the *[problem space]* for which the IT system is a solution.

Examples of domains include customer relationship management, financial loan application management, video subscription services, and so on.

Defining the domain is as much about defining what the software will _not_ do as what it _will_ do. The domain is the boundary within which the software will operate, or the context in which the software will be used.

A *subdomain* is a subset of a domain. It is a more focused area of knowledge or activity within a domain. Each subdomain has a specific purpose or represents a particular business capability. For example, in a video subscription service, the billing, video streaming, and user management areas might be subdomains.

An *link:./ontology.adoc[ontology]* is a formal representation of the concepts within a domain and the relationships between them. In *link:./domain-driven-design.adoc[domain-driven design]*, a *link:./domain-model.adoc[domain model]* captures the concepts and relationships within a domain, and the domain is expressed using one or more *ubiquitous languages* (ie. ontologies).

The *domain*, it's *subdomains* and language, are defined through collaboration between software developers and *[domain experts]* (aka. subject matter experts. The language used in the ontologies should be derived from the real world language used by the *domain experts]*.
