= Evolvability (aka. changeability)

Evolvability is a *link:./quality-attribute.adoc[quality attribute]* of a system. It refers to the ability to make changes to the _design_ of a system without breaking existing functionality. The ultimate in evolvability is *[evolutionary architecture]*, where the fundamental structure of the system, its data structures and the communication patterns between its components, can evolve over time.

The quality of evolvability is more important in the context of *link./distributed-system.adoc[distributed software]* than it is in *link:./monolith.adoc[monolithic software]*. Distributed software is inherently complex (it has a high degree of *link:./complexity.adoc[essential complexity]*), and therefore the ability to evolve the system over time becomes a key design constraint.

*link:./event-driven-architecture.adoc[Event-driven architecture]* is widely recognized as offering a high degree of evolvability in distributed software. The loosely coupled nature of event-driven systems means that you can change one part of the system without having to change other parts, and the interfaces between components (in the form of event messages) tend to be more stable than messages and direct method calls.
