= Kubernetes (K8s)

Kubernetes is an open-source *link:./container-orchestration.adoc[container orchestration]* platform that automates the deployment, scaling, and management of containerized applications. It was originally developed by Google and is now maintained by the Cloud Native Computing Foundation.

Red Hat's https://www.redhat.com/en/technologies/cloud-computing/openshift[OpenShift] is built on top of Kubernetes, providing additional features and tools for developers and operators. https://knative.dev/[Knative] is another open source project that extends Kubernetes, optimizing it for deployment of event-driven systems to *link:./serverless-computing.adoc[serverless]* platforms.

*link:./cloud-service-providers.adoc[Cloud service providers]* also offer managed Kubernetes services, such as Amazon Elastic Kubernetes Service (EKS), Google Kubernetes Engine (GKE), and is Google's Azure Kubernetes Service (AKS). Kubernetes-as-a-Service platforms include https://www.rancher.com/[Rancher] and https://www.portainer.io/[Portainer].

// TODO: https://aws.amazon.com/what-is/kubernetes-cluster/
