= Message-driven architecture (MDA)

Message-driven architecture (MDA) is a *[software architecture pattern]* that promotes the production,
consumption, and routing of messages, delivered *link:./asynchronous-communication.adoc[asynchronously]*
via *[message brokers]*, between software components.

Messages are an abstraction of a piece of data that represents an event, a command, or a query.
Therefore, broadly, the three types of messages are:

* *Commands*
* *Events*
* *Queries*

Commands and events are very similar. The difference is mostly just in the statement of intent that
underpins their semantics, whether the message is telling another component to do something (command),
or informing other components that something has happened (event). And queries are just one component
asking for a piece of data from whatever other component can provide it.

Thus, *[event-driven architecture]* can be seen as a subset of message-driven architecture, where
events are the primary type of message.


