= Microservices (aka. microservices architecture)

Microservices are a subset of *link:./service-oriented-architecture.adoc[service-oriented architecture (SOA)]* pattern.

The terms microservices and SOA are used interchangeably, but correctly microservices are a subset of SOA in which each service is very small, scoped only to a single business function, and independently deployable. There is no definitive list of features that distinguish microservices from more service-oriented designs, but the following characteristics are widely acknowledged:

.Microservices vs. SOA
[cols="1,2,2"]
|===
| Characteristic | Microservices | SOA

| *Granularity*
| Fine-grained services, often each with only a single responsibility.
| Mix of fine-grained and coarse-grained services. Some services may have multiple responsibilities.

| *Communication*
| Typically use lightweight protocols like HTTP.
| May use more complex communication protocols like SOAP.

| *Coupling*
| Typically use asynchronous communication patterns to reduce coupling between components.
| May have higher use of direct synchronous communication between services. Higher risk of evolution into "distributed monolith".

| *Technology*
| Encourages use of different languages and technology stacks to optimize individual services for their use cases.
| More likely to use a uniform technology stack across services.

| *Data*
| Each service manages its own data stores and caching layers.
| Services may share common data stores and caches.

| *Deployment*
| Services are independently deployable. Emphasizes continuous deployment and DevOps practices.
| There may be a higher degree of interdependence between services, limiting the "continuous" velocity of deployments.
|===

The distinction between SOA and microservices is really one of granularity. Microservices are typically smaller and more narrowly scoped in their responsibilities than services in a service-oriented architecture. The term "microservices" originated in the early 2010s and was popularized by thought leaders such as Martin Fowler and James Lewis. Subsequently, the term *[nanoservices]* has been used to describe services that are even more granular than microservices.

== Design trade-offs

A microservices architecture makes the same trade-offs as *link:./service-oriented-architecture.adoc[service-oriented architecture]* and any *link:./distributed-system.adoc[distributed system]* design. In addition, due to the increased number of services and the increased granularity of their individual responsibilities, the following trade-offs are common:

* Microservices tend to require a high degree of data replication between services, increasing *[accidental complexity]* associated with achieving data *[consistency]*.

* Microservices tend to be modeled with greater use of indirect, asynchronous communication, using message queues or event buses to handle message passing between services, rather than direct service-to-service calls, which would otherwise proliferate and greatly increase the complexity of the overall system design.

* Microservices require a higher degree of coordination between teams to deploy system-wide changes. If a change is made to one service's API, all dependent services will need to be updated. Well-defined *[service contracts]*, with versioning, are essential to managing this complexity. But cross-team communication and collaboration cannot be avoided entirely when it is necessary to incrementally migrate system-wide changes in a non-breaking way. The more services you have, the more complex this coordination becomes.

* Microservices are more complex to operate than systems built from coarser-grained services. Microservices tend to require more sophisticated deployment and monitoring tools, and more complex testing strategies – potentially including advanced techniques like *[chaos engineering (aka. chaos testing)]*. Debugging production issues can be challenging. You can't just attach a debugger to a running process if the source of a problem could be in any one of a number of downstream services. *[Observability]* tools, and especially *[distributed tracing]*, are specifically designed to solve the problem of debugging highly distributed systems like microservices.

* Infrastructure costs can actually be higher in a microservices system, due to the increased number of services and the need for additional technical services like *[service discovery]* and *[API gateways]*.

A well-regarded approach to implementing microservices in greenfield projects is to start with a *link:./modular-monolith.adoc[modular monolith]* and incrementally extract services from it as *[load]* on the system increases over time.

[quote, Martin Fowler]
____
Don't design microservices, extract them.
____

However, there is one scenario in which you should probably start with microservices, or some other distributed system design, and that's when you know the system will have large amounts of load as soon as production traffic is routed to it – for example, if you are replacing an existing system, or hooking into existing processes, the traffic patterns for which are already known.

See also the *link:./stranger-fig-pattern.adoc[strangler fig pattern]*, which is an architectural pattern to help with evolving legacy systems into modern architectures and technology stacks.

== Related links

* https://microservices.io/[Microservices.io] — Articles, a glossary of microservice-related terminology and design patterns, and many more resources, curated by Chris Richardson. An excellent starting point to learn about microservices architecture.

* https://martinfowler.com/articles/microservices.html[Microservices: A definition of this new architectural term] — By Martin Fowler and James Lewis. See also https://martinfowler.com/articles/microservice-trade-offs.html[Microservice trade-offs] for a concise summary of the pros and cons of microservices architecture, and Fowler's https://www.youtube.com/watch?v=wgdBVIX9ifA[GOTO 2014 talk] on this subject.

* https://www.nginx.com/resources/library/microservices-reference-architecture/[Microservices reference architecture], Chris Stetson (2017)

* https://thenewstack.io/ten-commandments-microservices/[10 commandments of microservices], The New Stack (2016)

* https://www.vinaysahni.com/best-practices-for-building-a-microservice-architecture[Best practices for building a microservices architecture], Vinay Sahni

* https://medium.com/@qasimsoomro/building-microservices-using-node-js-with-ddd-cqrs-and-event-sourcing-part-1-of-2-52e0dc3d81df[Building microservices: using Node with DDD, CQRS, and event sourcing], Qasim Soomro (2019)

* https://www.linkedin.com/pulse/designing-scalable-backend-infrastructures-from-scratch-chauhan[Designing scalable backend infrastructures from scratch], Anshul Chauhan

* https://blog.appdynamics.com/engineering/microservices-monoliths-and-self-contained-systems-time-to-break-it-down/[Microservices, monoliths, and self-contained systems] — Appydynamics Engineering

* https://www.sam-solutions.com/blog/microservices-vs-monolithic-real-business-examples/[Microservices vs. monolithic: real business examples] — Sam Solutions

* https://blog.buzachis-aris.com/2014/12/microservices-vs-monolithic-architectures/[Microservices vs monolithic architectures] — Buzachis Aris (2014)

=== Critiques

* https://riak.com/posts/technical/microservices-please-dont/[Microservices - please, don't], Sean Kelly (2016)

* https://www.dwmkerr.com/the-death-of-microservice-madness-in-2018/[The death of microservice madness in 2018], Dave Kerr (2018) — A strong case made why microservices is not a suitable architecture for all but a few very large organizations.

* https://thenewstack.io/beauty-beast-justgivings-microservices-transformation/[Microservices: the good, the bad and the hype], Jennifer Riggins, The New Stack (2017)

* https://blog.philipphauer.de/microservices-nutshell-pros-cons/[Microservices in a nutshell – pros and cons] — Philipp Hauer (2015)

* https://insights.sei.cmu.edu/saturn/2015/11/microservices-beyond-the-hype-what-you-gain-and-what-you-lose.html[Microservices beyond the hype: what you gain and what you lose] — Paulo Merson, SEI Insights (2015)

=== Case studies

* https://zepworks.com/posts/faster-better-cheaper-and-re-architecture/[Faster, cheaper and better: a story of breaking a monolith], Zep Dehpour (2019)

* https://www.youtube.com/watch?v=N1BWMW9NEQc[Airbnb, from monolith to microservices: how to scale your architecture] — Hear from Melanie Cebula, Software Engineer at Airbnb, on how they utilize microservices to scale their architecture.

* https://www.youtube.com/watch?v=57UK46qfBLY[Microservices at Netflix scale: principles, tradeoffs and lessons learned] — A talk by R. Meshenberg given at GOTO 2016.

=== Books

* https://www.amazon.com/gp/product/1491950358[Building Microservices: Designing Fine-Grained Systems] — Sam Newman (2015)

* https://www.nginx.com/resources/library/designing-deploying-microservices/[Designing and Deploying Microservices] — A free ebook, written by Chris Richardson and Floyd Smith on behalf of Nginx. An excellent resource for all involved in building and maintaining microservice-based systems.

* https://www.amazon.com/gp/product/1491965975/[Production-Ready Microservices: Building Standardized Systems Across an Engineering Organization] — Susan J. Fowler (2016)
