= Microservices (aka. microservice architecture)

The microservice pattern is a subset of *link:./service-oriented-architecture.adoc[service-oriented architecture (SOA)]*. There is no definitive list of features that distinguish microservices from more general service-oriented designs, but it is widely accepted that the difference is one of granularity. Microservices are typically very small, scoped to a single business function, and independently deployable thanks to maximized decoupling between services.

There also tends to be a bias toward *[asynchronous communication]* between services, and a preference for lightweight, indirect *[message-driven]* communication patterns, rather than direct service-to-service calls. These constraints do not necessarily apply to service-oriented architecture.

.Microservices vs. SOA
[cols="1,2,2"]
|===
|Characteristic |Microservices |SOA

|*Granularity*
|Fine-grained services, often each with only a single responsibility.
|Mix of fine-grained and coarse-grained services. Some services may have multiple responsibilities.

|*Communication*
|Preference for asynchronous *[messages]* and *[events]*, else lightweight request-response protocols like *[HTTP]*, *[TCP]*, *[UDP]* or *[WebSockets]*.
|May have a higher proportion of direct service-to-service calls, and may use more heavyweight communication protocols like *[SOAP]*.

|*Data*
|Each service manages its own data stores and caching layers.
|Services may share common data stores and caches.

|*Coupling*
|Services are very loosely coupled, with minimal direct dependencies between them. Ideally, individual services will be able to process requests without needing to call any other service.
|Higher use of direct synchronous communication between services, and possible shared data stores, increases coupling and risks evolution into "distributed monolith".

|*Technology*
|Encourages use of different languages and technology stacks to optimize individual services for their use cases.
|May use a uniform technology stack across all services.

|*Deployment*
|Services are independently deployable. Emphasizes continuous deployment and DevOps practices. Services have independent release schedules.
|There may be a higher degree of interdependence between services, limiting the "continuous" velocity of deployments. More traditional deployment patterns, eg. scheduled *[release trains]*.

|*Isolation*
|Greater fault tolerance of overall system, due to high degree of isolation of individual services.
|Greater degree of coupling between services reduces fault tolerance of the overall system.

|*Scalability*
|Individual services have considerable scope for scalability, especially horizontally.
|Larger, more coupled services tend to have more restricted scalability.

|*Operations*
|Services are operated by the team that built them.
|May be run by a central operations teams.

|*Team topologies*
|Each service is likely to be fully developed and operated by a single team.
|Multiple teams may be responsible for developing and operating some services.
|===

That final differentiating characteristic — the correlation between microservice architecture and *[team topologies]* — is particularly important. The functional boundaries between microservices tend to map directly to the responsibility boundaries between teams.

Microservice architecture allows for extreme scalability of computer systems. It also allows for extreme scalability of organizations. Microservice architecture is designed to solve the problem of how to scale the development and operation of a large, complex system across a very large organization. Traditional organizational structures — for example, where there are separate development and operations teams — tend to buckle under the weight of the communication overhead that comes with managing a large number of subsystems.

The ultimate goal of microservice architecture is to achieve the software delivery velocity of a start-up at enterprise scale.

Microservice architecture, when closely aligned with _team_ architecture, makes it possible for _thousands_ of people — spread across hundreds of small, independent teams — to contribute to the development and operation of a single large-scale system. This is achieved by composing a system from lots of very small components, each with a single narrowly-scoped responsibility, and with coupling between components all but eliminated. Crucially, each component is the exclusive responsibility of a single team. Individual services can be changed quickly, not only due to low coupling with other services but also due to limited requirements for coordination of changes between teams. *[Extreme programming]* practices like *[continuous deployment]* become possible even at huge scale.

Microservice architecture is a natural fit for the *[DevOps]* model of software development, where development and operations are closely aligned, and where the same team is responsible for the end-to-end development, testing, deployment, operation, maintenance, and support of a service — the "you build it, you run it" model. (See also *link:./cross-functional-teams.adoc[cross-functional teams]*.)

The term "microservices" originated in the early 2010s and was popularized by thought leaders such as Martin Fowler and James Lewis. Subsequently, the term *[nanoservices]* has been used to describe services that are even more granular than microservices.

== Design trade-offs

A microservice architecture makes the same trade-offs as *link:./service-oriented-architecture.adoc[service-oriented architecture]* and any other *link:./distributed-system.adoc[distributed system]* design. In addition, due to the increased number of services and the increased granularity of the services' individual responsibilities, the following trade-offs are made.

Finer-grained distributed systems like microservices are inherently more *link:./complexity.adoc[complex]* than coarser-grained ones. Complexity in software systems is derived primarily from the communication patterns between software components, more so than the overall system size. A system composed from lots of small services is in principle more complex than an equivalent system of the same overall size but composed of fewer, larger services. The more granular system design has a higher theoretical limit of interdependencies between its components, and therefore it has a higher potential for complex communication patterns.

image::./_/simple-vs-complex-distributed-systems.svg[]

There are more ways that a microservices system can fail. Each service, and each network call between services, is a potential *[point of failure]*. Therefore, more effort is required in the system design to build in *[fault tolerance]* mechanisms, such as *[retries]* and *[circuit breakers]*. This responsibility tends to be offloaded to dedicated infrastructure such as *[message queues]*, reducing the *[accidental complexity]* of individual services but increasing it for the overall system.

The choice of *[communication patterns]* and *[inter-process communication]* mechanisms is a critical design decision in microservices, and distributed systems more generally. In what form will inter-process communication be implemented, eg. RPC vs. message bus? And how will contracts between services be defined, enforced, and evolved?

Microservices tend to go hand-in-hand with *[asynchronous communication patterns]*, with a particular emphasis on *[message-driven]* (and especially *[event-driven]*) communication. The aim is to reduce, or eliminate entirely, direct service-to-service calls, which would otherwise be prolific due to the high number of services. This also reduces the risk of *[evolutionary]* microservice designs degrading into "API hell", where the number of direct service-to-service calls becomes unmanageable and (worse still) anti-patterns like circular service calls emerge. Message-driven communication has benefits for maintainability, fault tolerance, and scalability, but with additional costs associated with the management and monitoring of asynchronous communication.

A best practice in microservice design is for each service to be able to be able to process every request without needing to call any other service. This design constraint improves *[fault tolerance*], because all requests can be fulfilled even if one or more dependency services are *[unavailable/offline]*. Points of failure are minimized.

An extreme implementation sees application-level services being able to process requests without _ever_ calling any other lower-level service. Besides improved fault tolerance, this design constraint minimizes *latency* in the end-to-end request-response cycle. It is achieved by implementing the *service dependency inversion* principle. Where one service depends on another, rather than *[pulling]* data from the dependency service, the dependency service instead *[pushes]* data to the dependent services, which caches the *[replica data]* ahead of time. *[Temporal coupling]* is reduced and application-level services need only interact with their own data stores to fulfil requests.

In general, microservices tend to have a high degree of *[data replication]* between services. The higher the granularity of components in a system design, the more likely it is that state will need to be shared between components. Microservice architecture emphasizes services owning their own data stores, to maintain *[conceptual integrity]* of the microservice design and to reduce some of the otherwise inherent costs of distributed systems such as *[latency]* and *link:./fault-tolerance.adoc[brittleness]*. Therefore, shared state must be replicated. With data synchronization constrained to asynchronous communication, there are particular challenges associated with achieving *[eventual consistency]*. Often, this is a significant source of accidental complexity in microservice systems.

Placing *[load balancers]* and *[failover]* systems in front of individual microservices allows for *[horizontal scaling]* and increased *[fault tolerance]* (the trade off being that the load balancer becomes a *[single point of failure]*, which in turn can be solved by *[clustering]* primary and failover load balancers).

Load balancing works particularly well with *stateless microservices*, which are small services that do not persist state between requests, and which may be deployed to *[function-as-a-service (FaaS)*] platforms like AWS Lambda. Otherwise, each microservice instance needs to share the same state, which means all instances must share the same data store. If the data store also needs to be replicated to handle the load, there are additional challenges to ensure *[consistency]*.

Load balancing of microservices that are designed to be *disposable* opens up many other opportunities for things like the design of *[deployment pipelines]*. If we can easily destroy microservice instances, and add new instances to the load balancer, then it becomes much easier to do things like *[rolling deployments]* (ie. *[continuous delivery]* of lots of *[micro releases]*) and *[auto-recovery]*. See *link:./load-balancing.adoc[load balancing]* for more on this.

****
A event-driven, stateless microservice architecture gives us a very scalable, very extensible, and very resilient application platform. Add in a continuous *deployment pipeline* and you can do thousands of releases, to hundreds of microservices, without a moment of downtime.
****

A key objective of microservice architecture is to allow for individual services to be independently developed, deployed, and operated. Nevertheless, the delivery of changes to user-facing functionality inevitably requires coordination of development and deployment across services. Due to the high granularity of microservices, the communication overhead associated with managing system-wide changes can be significant. Business planning and prioritization can also be more challenging if input such as delivery *[estimations]* need to be gathered from multiple teams.

For the same reason, managing internal breaking API changes also requires careful coordination. Well-defined *[service contracts]*, with versioning, go some way to offsetting these challenges, but cross-team communication and collaboration cannot be avoided entirely when it is necessary to incrementally migrate system-wide changes in a non-breaking way. The more services you have, the more complex this coordination becomes.

Due to the inherent complexity of microservice architectures, sophisticated testing, deployment, and monitoring strategies are required. *[Integration testing]* is particularly challenging, and tends to be dependent upon service *[mocking]*, which reduces confidence in the tests. *[End-to-end]* testing requires a significant investment in infrastructure (to run a complete production replica) and such tests can be slow to run.

Advanced testing techniques like *[chaos engineering (aka. chaos testing)]* may be necessary in very large scale and mission critical systems.

Debugging production issues is more difficult, because you can't just attach a debugger to a running process if the issue could be in any downstream service. *[Observability]* tools, and especially *[distributed tracing]*, are specifically designed to solve the problem of "it works on my machine" syndrome when debugging highly distributed systems like microservices.

In general, infrastructure costs can be very high for microservice systems. Although individual services can be finely optimized for their specific use cases and traffic patterns, there are many additional technical services to run in production like *[service discovery]*, *[load balancers]*, and *[API gateways]*. In addition, non-production infrastructure to automate testing and deployment can become extensive. *[Cloud infrastructure]* systems, and especially *[public clouds]* which provide many of these as *[managed services]*, can reduce the costs associated with transitioning to microservice architecture in the short term, while tool such as *[infrastructure as code]* can further reduce the cost of managing such infrastructure over the longer term.

In addition to the technical trade-offs of the microservice architecture, there are also impacts on organizational structure, and even the culture and values of an organization.

To realize the full benefits of a microservice architecture, microservice teams require a high degree of *[autonomy]*, for example over their *[ways of working]* and *[technology choices]*. This autonomy is necessary to allow individual services to change quickly, but it also requires a high degree of *trust* from the organization. Microservices tend not to work so well in command-and-control organizations, where *[top-down design]* and decision-making is the norm.

Greater flexibility over technical choices within individual services is a benefit at the team level, but *technical sprawl* becomes a risk at the organization level. Additional effort needs to be made on *technical standardization* to maintain component *[cohesion]*, eg. through organization-level *technical standards* and *documentation*, development of shared code libraries, and additional organizational structures such as *guilds* and *communities of practice*. Organization-level policies such as *[service-level agreements]* and *API versioning* standards will be necessary to ensure that services are built and operated to a consistent standard. These added requirements increase the range of skills required within an organization, particularly for things like *architecture*, *modeling*, and *technical writing*.

.Libraries and microservices
****
Shared libraries are not incompatible with service-oriented designs. They can be useful to encapsulate much of the common boilerplate and cross-cutting concerns that are shared by all services in a system, things like logging, monitoring, security, etc.
****

All of this is additional overhead – work that does not directly contribute to delivering *[value]* to users.

Microservice architecture has other risks and costs for the operational model of organizations. For example, as teams become more specialized and focused on their own services, shared understanding of the whole system reduces. *Organization sprawl* becomes as much of a risk as *technical sprawl* does. New organization-level procedures will be needed to counter-balance this. For example, *cross-training* schemes may be required to support the transferability of team members between teams, and to reduce risks associated with the *[bus factor]*.

And, since no single team is responsible for the system's overall health and performance, accountability becomes a much more nuanced issue. The SLA for each service may be to respond to 90% of requests within 150ms. But who is accountable for the latency of the whole system – which will be the sum of the latencies of all the services in the dependency tree?

A microservice architecture may even have implications for recruitment strategies. The *[two-pizza team]* model, where teams are small enough that they can be fed with two (large) pizzas, is often cited as an effective team size for microservice teams. But given the breadth of responsibilities that are placed on microservice teams, this constraint means that individual team members shoulder a lot of responsibilities. For this reason, *generalization* tends to be more sought after in microservice teams than *specialization*. In a microservice team, everyone needs to be able to do a bit of everything. This has further trade-offs, risks, and costs. There are implications for productivity. Specialization tends to increase productivity, while generalization does the opposite. And there are increased risks associated with *burnout* and staff *turnover*. *[Self-service]* *[cloud infrastructure]* provisioning, *[auto-scaling]* and *[auto-recovery]* mechanisms, and centralized *[DevOps toolchains]*, go some way to reducing the responsibilities placed on individual teams.

In summary, for an organization looking for evolve their systems to microservices, the process is as much about organization change as it is technical change.

Microservices were popularized by companies like Amazon, Netflix, and Uber, who adopted this architectural style to solve the challenges of delivering planet-scale software-as-a-service. But for many organizations, the costs and complexity of microservices will outweigh the benefits. Microservices are not a *[silver bullet]*, but a pattern for solving a very particular set of *[scalability]* challenges – both technical scalability and organizational scalability.

== Best practices in microservice design

Most of the decisions to be made in the implementation of a microservice architecture involve trade-offs between local standardization and global standardization, and choosing the boundaries between services (and therefore determining the granularity of the overall system design).

A best practice that has emerged in microservice design is for microservice teams to work in a very thin application layer that is globally-standardized. Hardware (servers, operating systems, databases), communication infrastructure (*[service registry]* and *[service discovery]*, *[message]* and *[event]* handling, *[load balancing]*), operations infrastructure (*[configuration management]*, *[monitoring]* and *[logging]*, *[deployment pipelines]*), and even the application runtime platform (self-service tools, dev and test environments) are all abstracted away and centrally managed. Microservice teams have autonomy over a well-defined range of local standards, such as the implementation of business logic and choices of data storage technologies for their services.

Deep global standardization of a microservice system allows for new microservices to be easily added and quickly scaled. Cross-cutting concerns such as performance benchmarking and security testing can be managed centrally, and shared *[quality gates]* can help to enforce service level agreements and promote a high level of consistency in design and implementation across the whole system.

There's an even more critical balancing act in terms of the level of granularity of a microservice architecture design. If you over-fragment a system, the weight of managing a very large number of services will potentially negate the value of having very small, highly decoupled components. If you under-fragment a system, you get fewer of the benefits of microservices.

A second best practice that has emerged in microservice design is to deign services (and the team structures that align to them) around business verticals. Service boundaries should maps to business units or capabilities, such that the overall system becomes a model of the business domain. *[Domain-driven design]* is a useful approach to microservice design, for this reason.

Following the domain-driven design approach to microservices may not necessarily produce a pure microservice design. If services are designed to model real-world business subdomains, and if some of those subdomains are naturally quite extensive in their scope and responsibilities, then the design process may see some services emerge that are relatively large and complex. This is okay. The focus on a microservice design – indeed, on any distributed system design – should be on simplifying the system's internal communication patterns, not on *[decomposing]* the system into the smallest possible components. Indeed, it may even be desirable that some services span multiple subdomains (or a single bounded context).

A well-regarded approach to implementing microservices in greenfield projects, particularly when functional requirements are volatile or the business domain is not well understood from the start, is to begin with a *link:./modular-monolith.adoc[modular monolith]* and incrementally extract services from it as specific *[scalability]* requirements *[emerge]* over time.

[quote, Martin Fowler]
____
Don't design microservices, extract them.
____

This approach to microservice design means you do not risk *[prematurely optimizing]* the system design for problems that you may not ever have. Also, because it is much easier to *[refactor]* the internal structure of a *[monolith]* than it is to change the structure of a distributed system, you can more rapidly iterate a system's domain model and functionality in the early stages of development – exactly the time in a product's life cycle when requirements are at their most volatile. Development effort can focus on optimization once functional requirements are more stable.

The key principle in this approach is to delay extracting services until the communication patterns between them have already been optimized in the monolith. The danger in hurrying to a microservice design is ending up with a distributed *[ball of mud]*, where services are tightly coupled and have complex communication patterns between them. Monolithic balls of bud can be refactored more easily than distributed ones. If your organization does not have the *[capability maturity]* to build a decent monolith, it will only fail quicker with microservices.

[quote, Hadi Hariri, The Silver Bullet Syndrome – https://www.youtube.com/watch?v=3wyd6J3yjcs]
____
[With microservices you] move from a single ball of mud to orchestrating a lot of shit.
____

In most cases, system designs should not start with a microservice architecture. The one exception is when you know the system will have a large amount of load as soon as production traffic is routed to it, for example if you are replacing a legacy system or hooking into some existing process, for which the traffic patterns are already known. Implementing microservices through incremental decomposition of a monolith can also be an effective method for transitioning away from legacy systems. This approach requires comprehensive *[system (e2e) tests]*, so that you can verify that the system as a whole remains stable.

See also the *link:./strangler-fig-pattern.adoc[strangler fig pattern]*, which is an architectural pattern to help with evolving legacy systems into modern architectures and technology stacks.

''''

== References

* https://microservices.io/[Microservices.io] — Articles, a glossary of microservice-related terminology and design patterns, and many more resources, curated by Chris Richardson. An excellent starting point to learn about microservice architecture.

* https://martinfowler.com/articles/microservices.html[Microservices: A definition of this new architectural term] — By Martin Fowler and James Lewis. See also https://martinfowler.com/articles/microservice-trade-offs.html[Microservice trade-offs] for a concise summary of the pros and cons of microservice architecture, and Fowler's https://www.youtube.com/watch?v=wgdBVIX9ifA[GOTO 2014 talk] on this subject.

* https://smartbear.com/learn/api-design/microservices/[What are microservices], SmartBear

* https://www.nginx.com/resources/library/microservices-reference-architecture/[Microservices reference architecture], Chris Stetson (2017)

* https://thenewstack.io/ten-commandments-microservices/[10 commandments of microservices], The New Stack (2016)

* https://www.vinaysahni.com/best-practices-for-building-a-microservice-architecture[Best practices for building a microservice architecture], Vinay Sahni

* https://medium.com/@qasimsoomro/building-microservices-using-node-js-with-ddd-cqrs-and-event-sourcing-part-1-of-2-52e0dc3d81df[Building microservices: using Node with DDD, CQRS, and event sourcing], Qasim Soomro (2019)

* https://www.linkedin.com/pulse/designing-scalable-backend-infrastructures-from-scratch-chauhan[Designing scalable backend infrastructures from scratch], Anshul Chauhan

* https://blog.appdynamics.com/engineering/microservices-monoliths-and-self-contained-systems-time-to-break-it-down/[Microservices, monoliths, and self-contained systems] — Appydynamics Engineering

* https://www.sam-solutions.com/blog/microservices-vs-monolithic-real-business-examples/[Microservices vs. monolithic: real business examples] — Sam Solutions

* https://blog.buzachis-aris.com/2014/12/microservices-vs-monolithic-architectures/[Microservices vs monolithic architectures] — Buzachis Aris (2014)

=== Critiques

* https://riak.com/posts/technical/microservices-please-dont/[Microservices - please, don't], Sean Kelly (2016)

* https://www.dwmkerr.com/the-death-of-microservice-madness-in-2018/[The death of microservice madness in 2018], Dave Kerr (2018) — A strong case made why microservices is not a suitable architecture for all but a few very large organizations.

* https://thenewstack.io/beauty-beast-justgivings-microservices-transformation/[Microservices: the good, the bad and the hype], Jennifer Riggins, The New Stack (2017)

* https://blog.philipphauer.de/microservices-nutshell-pros-cons/[Microservices in a nutshell – pros and cons] — Philipp Hauer (2015)

* https://insights.sei.cmu.edu/saturn/2015/11/microservices-beyond-the-hype-what-you-gain-and-what-you-lose.html[Microservices beyond the hype: what you gain and what you lose] — Paulo Merson, SEI Insights (2015)

=== Case studies

* https://zepworks.com/posts/faster-better-cheaper-and-re-architecture/[Faster, cheaper and better: a story of breaking a monolith], Zep Dehpour (2019)

* https://www.youtube.com/watch?v=N1BWMW9NEQc[Airbnb, from monolith to microservices: how to scale your architecture] — Hear from Melanie Cebula, Software Engineer at Airbnb, on how they utilize microservices to scale their architecture.

* https://www.youtube.com/watch?v=57UK46qfBLY[Microservices at Netflix scale: principles, tradeoffs and lessons learned] — A talk by R. Meshenberg given at GOTO 2016.

=== Books

* https://www.amazon.com/gp/product/1491950358[Building Microservices: Designing Fine-Grained Systems] — Sam Newman (2015)

* https://www.nginx.com/resources/library/designing-deploying-microservices/[Designing and Deploying Microservices] — A free ebook, written by Chris Richardson and Floyd Smith on behalf of Nginx. An excellent resource for all involved in building and maintaining microservice-based systems.

* https://www.amazon.com/gp/product/1491965975/[Production-Ready Microservices: Building Standardized Systems Across an Engineering Organization] — Susan J. Fowler (2016)
