= Monolith (aka. monolithic architecture)

There is no definitive definition of what is a software monolith, but generally the term is used to refer to any software system in which all the code is maintained in one *[repository]* and the whole application runs in a single process (ie. it is a *single-node* application).

Before we had *link:./distributed-system.adoc[distributed systems]*, all software applications were developed as monoliths.

Still today, monoliths are a great way to start building out new software systems from scratch. Starting with a monolith means you can prototype, build, test, and ship new software products quickly. Monoliths also have some *[performance]* benefits. For example, *[latency]* is low, because all the code runs in the same process.

However, monoliths get harder to develop, deploy, and operate as time goes on. You cannot easily scale up the teams who maintain monolithic systems. Monoliths are risky to deploy updates to because every change, no matter how small, requires the whole system to be redeployed. And it tends to be expensive to scale the infrastructure on which monoliths run, because you can't target extra resources at the specific parts of the system that need them.

In summary: monoliths do not scale well.

Monoliths also tend to have lower *link:./fault-tolerance.adoc[fault tolerance]* than distributed systems. If one part of a monolith fails, the whole system tend to go down, because it all runs in the same process.

For these reasons, modern software-as-a-service products tend to be built as distributed systems, commonly designed around variations of *link:./service-oriented-architecture.adoc[service-oriented architecture]*.

*link:./modular-monolith.adoc[Modular monoliths]* are a halfway point between monoliths and distributed systems. They offer a mix of the simplicity of monoliths and the scalability of distributed systems, as modules can be incrementally extracted into independent services as the system's *[throughput]* and *[load]* grows over time.
