= The Mythical Man-Month

The "Mythical Man-Month: Essays on Software Engineering" is a famous book in the field of software
development, written by Frederick P Brooks Jr in 1975.

Brooks has worked on IBM's OS360 project, which was an important product because it introduced
several innovative features including device independent I/O and external library management.

Several concepts and metaphors introduced in The Mythical Man-Month have persisted in popular
software development culture. For example, in chapter one, Brooks uses the metaphor of a *tar pit*
to represent the problems associated with building large-scale computer programs. The more you
struggle with the problems, the more you get stuck. No one thing seems to be underlying cause of
the difficulties, but rather a combination of intractable problems make it difficult to move
forward. Some of these factors often could not have been unforeseen.

In the second chapter, Brooks introduces his main thesis: that poor scheduling estimations are the
single biggest factor in software project failures, and once a project is behind schedule you can't
solve the problem by adding more people to the project. He uses the term "man-month" to represent
one unit of additional manpower (one person working for one month).

Brooks identifies that one of the reasons why adding more people to a late project tends to slow
down, rather than speed up, development velocity is that additional people increase the
communication overhead within the delivery teams. Additional communication overhead increases the
completion time, and this is only partially (not wholly) offset by the additional programming
resource.

.Brook's Law
****
Adding manpower to a late software project makes it later.
****

On the reasons for poor estimations, Brooks identifies that coding is often the easiest phase to
accurately predict, but effort required to test and debug is often underestimated. At the time the
book was written, testing and debugging phases where separate from construction and scheduled only
after the first complete build.

In the third chapter, Brooks introduces the idea of the *surgical team* as his proposed solution
to the problems of large-scale software development in that era of computing. Brooks observes that
many program managers believe they are better off have a small number of very skilled programmers
on their team, rather than a large number of mediocre ones!

Brooks argues that large-scale projects should be broken down into smaller subsystems, with each
subsystem built by one small, independent team. Each team should operate similarly to a surgical
team in a hospital. Each team would have a chief programmer, the surgeon, who is in charge of the
whole thing. The rest of the team members try to help him complete the project (the surgery).

The leaders of the surgical teams also collaborate with each other, to coordinate the work on the
subsystems so they can be successfully integrated together to compose a complete solution. Thus,
communication overhead throughout the overall project is minimized by having a hierarchy of
delivery teams, each working on discrete subsystems of the overall solution.

In a surgical team, the whole project is the brainchild of the surgeon. The surgeon is responsible
for defining and maintaining the *conceptual integrity* of the solution. By comparison, Brooks
writes, in *collaborative teams* everyone is equal and everyone can have input into the direction
of the project, even if this sometimes causes chaos.

Brooks defines *conceptual integrity* in chapter four. He argues this is probably the most important
aspect of large system programming, but one that is often overlooked as programmers have a tendency
to focus on the design of individual features rather than the design of the overall system. Brooks
argues that large-scale systems should have a consistent design philosophy flow through all
subsystems. It is better to have one good idea and carry it through the project, than having
several uncoordinated good ideas.

Conceptual integrity can be preserved, Brooks argues, by having one system architect who designs
the whole system from top-to-bottom. Brooks argues that the system architect should stick with
the design of the system, and not get involved with the implementation. Implementation and design
should be treated as two separate phases. A system architect defines the design specifications,
while the builders define the implementation specifications. System architecture should be based
on user requirements.

Chapter seven is another important chapter in the book. Brooks uses the biblical story of the Tower
of Babel as a metaphor for the communication breakdowns that can occur in large software projects.
Originally, the people of Babel spoke the same language and they were all united. Babel fell when
the people started speaking different languages and could no longer communicate with each other.
The Tower of Babel failed not because of technological limitations or a lack of resources, but
because of communication problems and the disorganization that resulted from them.

The same thing is the cause of many failures in the delivery of large computer systems, Brooks
argues. To improve communication within a large project, Brook suggests keeping a *workbook*
for the project. The workbook contains all the documentation relevant to the project, from high-level
missions and objectives, via external specifications (what we would now call user acceptance
criteria), to internal specifications and design documents. Critically, the workbook must also
record the changes made to the project over time. Changes to the contents of the workbook should
also be recorded.

As the workbook increases in size, it become more important to impose a strict structure to its
contents. Indexing and numbering systems may be used to help people find the information they're
looking for.

In chapter 11, titled "Plan to Throw One Away", Brooks proposes building *pilot models* or
*pilot systems* as an intermediate step between the initial system design and the construction
of the final system. The pilot system helps to identify potential problems with the design before
the final solution is built. The pilot system should be thrown away and not given to the customer.
This is because the pilot model often has bugs in it, which would reduce the customer's confidence
in the producer.

In chapter 14, Brooks suggests the use of [PERT charts] to keep track of critical tasks in a
project. Chapter 15 provides guidance on documenting large programs. The book also summarizes
modelling notations that were popular at the time, and he draws comparisons between [top-down]
and [bottom-up] approaches to system design.

Many of the ideas introduced by Brooks in The Mythical Man-Month are still pertinent to software
development today. But some ideas have been superseded. That design, construction, and testing
should be treated as distinct phases is no longer considered best practice, for example.
