= The Mythical Man-Month

The "Mythical Man-Month: Essays on Software Engineering" is a famous book in the field of software development, written by Frederick P Brooks Jr in 1975.

Brooks has worked on IBM's OS360 project, which was an important product because it introduced several innovative features including device independent I/O and external library management.

Several concepts and metaphors introduced in The Mythical Man-Month have persisted in popular software development culture. For example, in chapter one, Brooks uses the metaphor of a *tar pit* to represent the problems associated with building large-scale computer programs. The more you struggle with the problems, the more you get stuck. No one thing seems to be underlying cause of the difficulties, but rather a combination of intractable problems make it difficult to move forward. Some of these factors often could not have been unforeseen.

In the second chapter, Brooks introduces his main thesis: that poor scheduling estimations are the single biggest factor in software project failures, and once a project is behind schedule you can't solve the problem by adding more people to the project. He uses the term "man-month" to represent one unit of additional manpower (one person working for one month).

Brooks identifies that one of the reasons why adding more people to a late project tends to slow down, rather than speed up, development velocity is that additional people increase the communication overhead within the delivery teams. Additional communication overhead increases the completion time, and this is only partially (not wholly) offset by the additional programming resource.

[quote, Brooks's Law]
____
Adding manpower to a late software project makes it later.
____

See my *blog post* for a more detailed discussion of the book and its themes.
