= NoSQL databases

"NoSQL" is an umbrella term for a range of *non-relational databases*, ie. database designs that
are not based on the traditional model of *link:./relational-databases.adoc[relational]*,
tabular data. NoSQL refers to any database management system that is based on schema-less data
models, and therefore does not require stored data to be highly structured.

The four main types of NoSQL databases are:

* *link:./document-oriented-databases.adoc[Document-oriented databases]*
* *link:./graph-databases.adoc[Graph databases]*
* *link:./key-value-stores.adoc[Key-value stores]*
* *link:./wide-column-stores.adoc[Wide-column stores]*

NoSQL databases offer more flexibility and easier scalability than relational databases, but may
sacrifice some of the *[data integrity]* and *link:./acid-principles.adoc[transactional guarantees]*
of relational databases.

NoSQL is suited for handling large volumes of unstructured or semi-structured data (in which data
structures may be changed, to some degree, on a per-record basis), and for applications requiring
quick iterations in the design of their data model.

Compared to *link:./relational-databases.adoc[relational databases]*, NoSQL databases are more
amenable to *link:./horizontal-scaling.adoc[horizontal scaling]*. Indeed, some NoSQL databases
systems are designed specifically to be distributed across multiple nodes. Examples include
*Cassandra* and *MongoDB*.

== Types of NoSQL databases

There are four main types of NoSQL databases:

* *Key-value stores*: Data is stored in an associative array, where a unique key maps to a specific
  value. Examples include Redis and DynamoDB.

* *Document databases*: Data is stored in documents, which are self-contained pieces of data that
  contain all the information needed to query and update the data. Examples include MongoDB and
  CouchDB.

* *Wide-column stores*: Data is stored in columns, rather than rows, which can be grouped together
  in column families. Examples include Cassandra and HBase.

* *Graph databases*: Data is stored in nodes and edges, which represent entities and the
  relationships between them. Examples include Neo4j and Amazon Neptune.

