= Ontology

An ontology is any formal representation of a set of concepts and categories in a subject area or *link:./domain.adoc[domain]*. It describes the concepts and relationships between them, and can be used to *link:./domain-engineering.adoc[model a domain]*, a subdomain, or a specific problem.

In *link:./domain-driven-design.adoc[domain-driven design]*, ontologies map to the concept of *link:./ubiquitous-language.adoc[ubiquitous language]*. The ubiquitous language is a shared vocabulary that all stakeholders in a project agree on, and it is used to describe all aspects of the domain (or, in complex domains, a group of subdomains defined by a *bounded context*).

Standards like RDF, RDF Schema, and the Web Ontology Language (OWL) can be used to create and reason about ontologies. Software modeling languages like UML can also be used for this purpose, for example class diagrams could be used to represent concepts and the relationships between them.

[Protégé] is a free and open source ontology editor and knowledge management system. It supports OWL and RDF.

[HybridMDSD] is a tool that integrates different domain-specific modeling languges based on their ontological foundations.
