= Performance

Performance is a *link:./quality-attributes.adoc[quality attribute]* that measures how well a system
responds to client or user interactions.

*Perceived performance* is a subset of performance that focuses on the _responsiveness_ of a
system in acknowledging user actions, rather than the longer time it takes to process those
actions. Perceived performance is often harder to measure, because it depends on the users'
_perceptions_ of the system's responsiveness.

Optimization techniques vary widely depending on the requirements and constraints of the system, and
are largely dictated by *link:./access-patterns.adoc[access patterns]*. For example, a system with
read-heavy workloads will be optimized very differently to one with write-heavy workloads.

Performance is synonymous with *speed* and *responsiveness*. It is closely related to *latency*,
which refers to measurements of the time it takes for a system to respond to input.

Colloquially, the term "performance" is widely used as a catch-all term for how well a system
meets all its functional and non-functional requirements. Thus, a high performing system may be
regarded as one tat strikes a good balance between *[latency]*, *[throughput]*, *[scalability]*,
*[availability]*, *[reliability]*, *[efficiency]* of resource utilization, and other quality
attributes.
