= Redundancy

In the context of a *link:./distributed-system.adoc[distributed software]*, redundancy refers to the duplication of critical components or functions of the system. Adding redundancy reduces *[single points of failure]*, so increasing *link:./fault-tolerance.adoc[reliability]* and *link:./availability.adoc[availability]*. If one part of the system fails, another can take over its tasks, minimizing *link:./downtime.adoc[downtime]* and preventing data loss.

Redundancy in distributed software can be applied to data, program code, hardware, and network components:

// TODO: https://www.egnyte.com/guides/governance/data-redundancy
// TODO: https://redis.io/blog/what-is-data-replication/
// TODO: https://thenewstack.io/techniques-for-scaling-applications-with-a-database/

* *Data redundancy*: Storing copies of the same data on multiple nodes.

* *Software redundancy*: Deploying multiple instances of the same application.

* *Hardware redundancy*: Using additional hardware components, such as servers.

* *Network redundancy*: Implementing multiple network paths and connections.

Redundancy is an important *link:./quality-attribute.adoc[quality attribute]* in distributed software that require high *link:./availability.adoc[availability]* and *link:./fault-tolerance.adoc[resilience]*. Examples of systems that have high levels of redundancy include data centres and the cloud services that are served from them.

*[Isolation]* is a complementary design principle. This is about limiting the impact of failures so that they don't affect the entire system. For example, if the primary node for a service fails, and if its failovers fail too, the rest of the system should continue to operate (albeit with reduced functionality).
