= Relational database management systems (RDBMS)

Relational database management systems (RDBMS), also known as *relational databases* or *SQL databases*, are built on the relational model that stores data against predefined schemas, and structured as interlinked tabular data. Each row in a data table typically maps to an entity or object, and the table's columns define the entity's fields.

These databases are highly structured and offer powerful *[query languages]*, usually a form of *[SQL]*, making them ideal for complex queries and transactions. Relational databases tend to be *link:./acid-principles.adoc[ACID compliant]*, making them good choices for applications that require *[data integrity]* be prioritized over performance.

Relational databases can be challenging to *[scale horizontally]*. They tend, instead, to be *link:./vertical-scaling.adoc[scaled vertically]* (the capacity of individual nodes is increased as data grows). However, *link:./sharding.adoc[sharding]* can also be used to distribute data horizontally across multiple RDBMS instances.

By comparison, *link:./nosql-databases.adoc[non-relational databases]* (aka NoSQL databases) are more flexible and scalable, but may sacrifice some of the consistency and transactional guarantees of relational databases.

== Examples of relational databases

* MySQL
* PostgreSQL
* SQLite
* Oracle Database

== See also

* *link:./database-query-optimization.adoc[Database query optimization]*
