= Scalability

Scalability is a *quality attribute* and of an IT system. It refers to the property of a system to
handle a growing amount of load – such as more data throughput, more concurrent users, or more
operations and transactions – by adding resources to the system.

A system that can continuously evolve, without major refactoring or re-architecting, to handle
a growing workload is said to be *scalable*.

== Scalability techniques

In broad terms, there are two main ways to scale a system:

*link:./horizontal-scaling.adoc[Horizontal scaling]* (aka. *scaling out*) means adding more nodes
to a system, such as adding more servers to a server farm.

And *link:./vertical-scaling.adoc[vertical scaling]* (aka. *scaling up*) means increasing the
capacity of individual nodes, such as using a more powerful server.

The following strategies are also relevant:

* *link:./caching.adoc[Caching]*
* *link:./failover.adoc[Failover]*
* *link:./load-balancing.adoc[Load balancing]*
* *link:./preprocessing.adoc[Preprocessing]*
* *link:./replication.adoc[Replication]*
* *link:./sharding.adoc[Sharding]*
