= Service-oriented architecture (SOA)

Service-oriented architecture is a *link:./distributed-systems.adoc[distributed system]* design
pattern. It sees an application divided into multiple services, each of which can be developed
and tested independently of other services within the system. Individual services will typically
have distinct code repositories and production infrastructure.

The *link:./system-design.adoc[system design]* of service-oriented architecture involves *[decomposing]*
an application's functionality into separate, *[loosely coupled]* services, each managing its own
data stores and caches, and which communicate with each via network APIs or message brokers.
Services will typically be scoped to *[bounded contexts]* or *[subdomains]* within the
application's *[domain*].

Common services found in many service-oriented systems include general-purpose services such as
authentication, user management, and payment processing. Other services will be domain-specific.
For example, an e-commerce platform may have services for inventory management, order processing,
and customer reviews.

== Comparisons to other architectural styles

*link:./microservices.adoc[Microservices architecture]* is a subset of service-oriented architecture
with further design constraints. A microservices architecture emphasizes the design of
small, independently deployable services.

*link:./message-driven-architecture.adoc[message-driven]* and *link:./event-driven-architecture.adoc[event-driven]*
architectures help to enforce the loose coupling between services that is a key principle of SOA.
However, SOA itself does not prescribe particular communication patterns for service contrcts, and
a service-oriented system may even implement a mix of communication styles, including
*[synchronous]* and *[asynchronous]* styles.

If each service in a service-oriented design were to deliver an end-to-end solution for a discrete
user-facing function, then the architectural style could be said to be a cross between
service-oriented and *link:./vertical-slice-architecture.adoc[vertical-slice architecture]*
In practice, SOA tends to see a hierarchy of services, in which lower-level services (particularly
stateless ones) are shared by the higher-level domain layer services.

// TODO: Diagrams

== Trade-offs

Advantages of service-oriented architecture include increased flexibility to optimize software
components in different ways for performance and scalability (potentially even using different
programming languages and tech stacks for different services), and greater system *[resilience]*
(when one service fails, the rest of the system can continue to function).

Service-oriented architecture tends to work best where *[bounded contexts]* map directly to team
topologies, allowing teams to work independently on different services.

See *link:./microservices.adoc[microservices]* for more notes on the pros and cons of
service-oriented distributed system designs.
