= Service mesh

Finally, you could use a *service mesh*. A service mesh handles all of the communication as well as
dealing with service discovery and reliability (load balancing etc).

A service mesh is a dedicated infrastructure layer that manages all aspects of service-to-service
communication within a *link:./distributed-systems.adoc[distributed system]*.

Typically, a service mesh will encompass the following features:

* *link:./load-balancing.adoc[Load balancing]*: Distributing traffic evenly across
  *link:/replication.adoc[replicated]* notes, improving *link:./fault-tolerance.adoc[resilience]*
  to failure of any single node.

* *[Service discovery]*: Allowing services to find and communicate with each other, typically
  through a *[service registry]*.

* *[Routing]*, *[retries]*, *[circuit breaking]* and other traffic management responsibilities.

* *link:./security.adoc[Security]*: Handling service-to-service authentication and authorization,
  and encryption of communication channels.

* *link:./observability.adoc[Observability]*: Providing *link:./monitoring.adoc[monitoring]* and
  *[tracing]* capabilities.

Popular service mesh solutions include [Istio] and [Linkerd].
