= Shell

A shell is a command-line interpreter that provides a user interface for accessing an operating system's services. It allows users to execute system commands, run utilities and other programs, and manage files and processes on the local system. The shell interprets user commands and translates them into actions performed by the operating system.

A *Unix shell* is a shell designed for Unix-like operating systems. A Unix shell is both a command language (in which commands are typed and executed interactively via the command line) and a scripting language (in which a sequence of commands are written in a file and executed all at once – behaving more like a program).

Well-known Unix shells include:

* The Bourne Shell, `sh`, one of the earliest shells.
* The Bourne Again Shell, `bash`, a superset of Bourne Shell functionality.
* https://bxr.su/NetBSD/bin/csh/[C Shell], `csh`, and the improved version https://www.tcsh.org/[tee-shell], `tcsh`.
* https://www.kornshell.org/[KornShell], `ksh`, which is backwards compatible with Bourne Shell and includes many of the features of C Shell.
* https://www.zsh.org/[Z Shell], `zsh`, another popular shell based on Bourne.

Lesser-known Unix shells include https://yash.osdn.jp/[Yash] and https://www.busybox.net/[busybox].

See also link:./posix.adoc[POSIX].
