= Stream processing systems

Stream processing systems are used to process continuous streams of data. They have many use cases,
including real-time analytics, data enrichments, observability and monitoring, and more.

Stream processing systems are used in *link:./event-driven-architecture.adoc[event-driven]* systems,
as an alternative to *[event buses]* and *link:./message-queues.adoc[message queues]*. While event
buses and message queues are used to decouple components in *link:./distributed-systems.adoc[distributed systems]*,
with the aim of making complex systems more modular and scalable, stream processing systems are
optimized for the *real-time* processing and analysis of data, though they can be used in the
implementation of conventional events and messages as well.

Stream processing systems are distinguished from message queues and event buses by their extremely
high *throughput*. Examples of stream processing systems include https://kafka.apache.org/documentation/streams/[Kafka Streams],
https://flink.apache.org/[Flink], and https://azure.microsoft.com/en-gb/products/stream-analytics/Azure Stream Analytics].

Other common features of stream processing systems include *data retention* and *replayability*. Messages
can be persisted until their *time-to-live (TTL)* expires. In the meantime, those messages can be resent
to consumers.

Like event-driven systems, stream processing systems tend to implement *fan out* patterns, which means
multiple consumers can connect to the same queue (stream of data), each getting one copy of each message
in the queue. This allows multiple independent components to process data in different ways, eg. for logs,
data analysis, and real-time service updates.

