= Vertical-slice architecture

Vertical-slice architecture is a software design pattern where the application is divided into thin
slices that encompass all *link:./layered-architecture.adoc[layers]* of the system, from the user
interface to the data storage.

Each slice represents a complete function or feature of the application.

The distinguishing features of vertical-slice architecture:

* Emphasizes delivery end-to-end functionality for specific features or use cases.

* Decomposes code around features or user stories, rather than technical layers.

* Each slice contains all the layers – UI, business logic, data access – needed to implement a
  feature.

// TODO: Add diagrams

A *link:./service-oriented-architecture.adoc[service-oriented architecture]* or
*link:./microservices.adoc[microservices architecture]* may also use vertical feature slices to
define the scope and boundaries of each service. However, vertical slice architecture may be used
in monolithic applications as well. Code for each feature would reside in its namespace or directory,
or some other module or component system for organizing related code.

Benefits of vertical slice architecture include:

* Independent development, testing, and deployment of individual features.
* Rapid feature delivery, and therefore faster user feedback.
* Better alignment between delivery and business requirements.
* Reduced need for abstractions (eg. services, repositories) within each slice.
* Promotes cross-functional collaboration on individual features.

Disadvantages may include:

* Fragmentation of codebase by features increases duplication of logic and inconsistency in
  implementation patterns between features.
* Increased complexity in managing dependencies between features.
* Architecture emphasizes feature delivery over cross-cutting concerns like performance,
  scalability, and maintainability.

''''

.References
****
* https://jimmybogard.com/vertical-slice-architecture/[Vertical slice architecture], Jimmy Bogard (2018)
****
