= Web-oriented architecture (WOA)

Web-oriented architecture was coined in 2006 by Nick Gall of the Gartner Group. It is described as an extension of *link:./service-oriented-architecture.adoc[service-oriented architecture (SOA)]* but scoped specifically to web-based applications.

[quote, Nick Gall, https://web.archive.org/web/20081220010701/http://blogs.gartner.com/nick_gall/2008/11/19/woa-putting-the-web-back-in-web-services/]
____
WOA is an architectural substyle of SOA that integrates systems and users via a web of globally linked hypermedia based on the architecture of the Web. This architecture emphasizes generality of interfaces (UIs and APIs) to achieve global network effects through five fundamental generic interface constraints:

1. Identification of resources.
2. Manipulation of resources through representations.
3. Self-descriptive messages.
4. Hypermedia as the engine of application state.
5. Application neutrality.
____

The five interface constraints are an extension of the constraints of the *uniform interface* of REST as described in https://web.archive.org/web/20081218043754/http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm#sec_5_1_5[Roy Fielding's thesis]. "Application neutrality" is a new constraint, but one that the Gartner team considered to be implicit in REST.

Thus, web-oriented architecture could be described as a blend of SOA and REST constraints. In addition, WOA leverages *[HTTP]* and other web standards.

*link:./resource-oriented-architecture.adoc[Resource-oriented architecture (ROA)]* is a similar architectural style that is also based on REST principles.
